///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// Your custom recording code should go in this file.
// The designer will only add methods to this file, so your custom code won't be overwritten.
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace SQLDMTestAutomation.SQLDMRecordings
{
    public partial class CollapseAllServers
    {
        /// <summary>
        /// This method gets called right after the recording has been started.
        /// It can be used to execute recording specific initialization code.
        /// </summary>
        private void Init()
        {
            // Your recording specific initialization code goes here.
        }

         

        public void AllServersCollapse(RepoItemInfo argument1)
        {
             TreeItem item = null; bool isFound = false;
        	try 
        	{
        		//Report.Log(ReportLevel.Info, "Before", "AllServer Code", treeitemInfo);
        		Ranorex.TreeItem CollapseAllServers = repo.IderaSQLDiagnosticManagerSQLdmRepo.AllServers;
				//Report.Log(ReportLevel.Info, "After", "AllServer Code", treeitemInfo);        		
	        	foreach (var itemtree in CollapseAllServers.Items)
	        	{
	        		if(itemtree.Expanded)
	        		{
	        			itemtree.Collapse();
	        			System.Threading.Thread.Sleep(500);
	        		}
	        	}
        	} 
        	catch (Exception e)
        	{
        		throw e;
        	}
        }

    }
}
