///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace SQLDMTestAutomation.SQLDMRecordings
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The PerformQueryOperations recording.
    /// </summary>
    [TestModule("1a2b45b0-2c4a-422a-b00c-b3e8d8036959", ModuleType.Recording, 1)]
    public partial class PerformQueryOperations : ITestModule
    {
        /// <summary>
        /// Holds an instance of the SQLDMTestAutomation.SQLDMTestAutomationRepository repository.
        /// </summary>
        public static SQLDMTestAutomation.SQLDMTestAutomationRepository repo = SQLDMTestAutomation.SQLDMTestAutomationRepository.Instance;

        static PerformQueryOperations instance = new PerformQueryOperations();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public PerformQueryOperations()
        {
            Query = "select [QueryMonitorTopPlanCountFilter],[QueryMonitorTopPlanCategoryFilter],[QueryMonitorQueryStoreMonitoringEnabled] from MonitoredSQLServers";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static PerformQueryOperations Instance
        {
            get { return instance; }
        }

#region Variables

        string _Query;

        /// <summary>
        /// Gets or sets the value of variable Query.
        /// </summary>
        [TestVariable("b64c7459-2791-4ac7-946e-49f112766854")]
        public string Query
        {
            get { return _Query; }
            set { _Query = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.2")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.2")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Application", "Run application 'C:\\Program Files (x86)\\Microsoft SQL Server\\100\\Tools\\Binn\\VSShell\\Common7\\IDE\\Ssms.exe' with arguments '' in normal mode.", new RecordItemIndex(0));
            Host.Local.RunApplication("C:\\Program Files (x86)\\Microsoft SQL Server\\100\\Tools\\Binn\\VSShell\\Common7\\IDE\\Ssms.exe", "", "C:\\Program Files (x86)\\Microsoft SQL Server\\100\\Tools\\Binn\\VSShell\\Common7\\IDE", false);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 5s for the attribute 'Text' to contain the specified value 'SQLDM Today'. Associated repository item: 'SQLDM.IderaSQLDiagnosticManagerSQLdmRepo.SQLDMToday'", repo.SQLDM.IderaSQLDiagnosticManagerSQLdmRepo.SQLDMTodayInfo, new RecordItemIndex(1));
            repo.SQLDM.IderaSQLDiagnosticManagerSQLdmRepo.SQLDMTodayInfo.WaitForAttributeContains(5000, "Text", "SQLDM Today");
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 20s.", new RecordItemIndex(2));
            Delay.Duration(20000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Move item 'SSMS.ConnectionDialog.ServerNameToConnect' at Center.", repo.SSMS.ConnectionDialog.ServerNameToConnectInfo, new RecordItemIndex(3));
            repo.SSMS.ConnectionDialog.ServerNameToConnect.MoveTo();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Ctrl+A' Press with focus on 'SSMS.ConnectionDialog.ServerNameToConnect'.", repo.SSMS.ConnectionDialog.ServerNameToConnectInfo, new RecordItemIndex(4));
            Keyboard.PrepareFocus(repo.SSMS.ConnectionDialog.ServerNameToConnect);
            Keyboard.Press(System.Windows.Forms.Keys.A | System.Windows.Forms.Keys.Control, Keyboard.DefaultScanCode, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'AUT-SQL-DEV-001' with focus on 'SSMS.ConnectionDialog.ServerNameToConnect'.", repo.SSMS.ConnectionDialog.ServerNameToConnectInfo, new RecordItemIndex(5));
            repo.SSMS.ConnectionDialog.ServerNameToConnect.PressKeys("AUT-SQL-DEV-001");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Move item 'SSMS.ConnectionDialog.Connect' at Center.", repo.SSMS.ConnectionDialog.ConnectInfo, new RecordItemIndex(6));
            repo.SSMS.ConnectionDialog.Connect.MoveTo();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SSMS.ConnectionDialog.Connect' at Center.", repo.SSMS.ConnectionDialog.ConnectInfo, new RecordItemIndex(7));
            repo.SSMS.ConnectionDialog.Connect.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Move item 'SSMS.MicrosoftSQLServerManagementStudio.Databases' at Center.", repo.SSMS.MicrosoftSQLServerManagementStudio.DatabasesInfo, new RecordItemIndex(8));
            repo.SSMS.MicrosoftSQLServerManagementStudio.Databases.MoveTo();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left DoubleClick item 'SSMS.MicrosoftSQLServerManagementStudio.Databases' at Center.", repo.SSMS.MicrosoftSQLServerManagementStudio.DatabasesInfo, new RecordItemIndex(9));
            repo.SSMS.MicrosoftSQLServerManagementStudio.Databases.DoubleClick();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Move item 'SSMS.MicrosoftSQLServerManagementStudio.SQLdmRepository' at Center.", repo.SSMS.MicrosoftSQLServerManagementStudio.SQLdmRepositoryInfo, new RecordItemIndex(10));
            repo.SSMS.MicrosoftSQLServerManagementStudio.SQLdmRepository.MoveTo();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Invoke action", "Invoking Select() on item 'SSMS.MicrosoftSQLServerManagementStudio.SQLdmRepository'.", repo.SSMS.MicrosoftSQLServerManagementStudio.SQLdmRepositoryInfo, new RecordItemIndex(11));
            repo.SSMS.MicrosoftSQLServerManagementStudio.SQLdmRepository.Select();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Right Click item 'SSMS.MicrosoftSQLServerManagementStudio.SQLdmRepository' at Center.", repo.SSMS.MicrosoftSQLServerManagementStudio.SQLdmRepositoryInfo, new RecordItemIndex(12));
            repo.SSMS.MicrosoftSQLServerManagementStudio.SQLdmRepository.Click(System.Windows.Forms.MouseButtons.Right);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Right Click item 'SSMS.SSMS_SomeContextMenu.NewQuery' at Center.", repo.SSMS.SSMS_SomeContextMenu.NewQueryInfo, new RecordItemIndex(13));
            repo.SSMS.SSMS_SomeContextMenu.NewQuery.Click(System.Windows.Forms.MouseButtons.Right);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SSMS.MicrosoftSQLServerManagementStudio.QueryEditor' at Center.", repo.SSMS.MicrosoftSQLServerManagementStudio.QueryEditorInfo, new RecordItemIndex(14));
            repo.SSMS.MicrosoftSQLServerManagementStudio.QueryEditor.Click();
            Delay.Milliseconds(200);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
