///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace SQLDMTestAutomation
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The AddServer recording.
    /// </summary>
    [TestModule("0d45aeec-90f8-4043-a0cf-91a511febd51", ModuleType.Recording, 1)]
    public partial class AddServer : ITestModule
    {
        /// <summary>
        /// Holds an instance of the SQLDMTestAutomationRepository repository.
        /// </summary>
        public static SQLDMTestAutomationRepository repo = SQLDMTestAutomationRepository.Instance;

        static AddServer instance = new AddServer();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public AddServer()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static AddServer Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.2")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.2")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'IderaSQLDiagnosticManagerSQLdmRepo.File' at Center.", repo.IderaSQLDiagnosticManagerSQLdmRepo.FileInfo, new RecordItemIndex(0));
            repo.IderaSQLDiagnosticManagerSQLdmRepo.File.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SomeContextMenu.ManageServers' at Center.", repo.SomeContextMenu.ManageServersInfo, new RecordItemIndex(1));
            repo.SomeContextMenu.ManageServers.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ManageServersDialog.AddButton' at Center.", repo.ManageServersDialog.AddButtonInfo, new RecordItemIndex(2));
            repo.ManageServersDialog.AddButton.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AddServersWizard.NextButton' at Center.", repo.AddServersWizard.NextButtonInfo, new RecordItemIndex(3));
            repo.AddServersWizard.NextButton.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AddServersWizard.NextButton' at Center.", repo.AddServersWizard.NextButtonInfo, new RecordItemIndex(4));
            repo.AddServersWizard.NextButton.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'JS-XW7S8\\SQL2008' with focus on 'AddServersWizard.Text'.", repo.AddServersWizard.TextInfo, new RecordItemIndex(5));
            repo.AddServersWizard.Text.PressKeys("JS-XW7S8\\SQL2008");
            Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Set value", "Setting attribute Text to 'JS-XW7S8\\SQL2008' on item 'AddServersWizard.Text'.", repo.AddServersWizard.TextInfo, new RecordItemIndex(6));
            //repo.AddServersWizard.Text.Element.SetAttributeValue("Text", "JS-XW7S8\\SQL2008");
            //Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{ENTER}' with focus on 'AddServersWizard.Text'.", repo.AddServersWizard.TextInfo, new RecordItemIndex(7));
            repo.AddServersWizard.Text.PressKeys("{ENTER}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AddServersWizard.NextButton' at Center.", repo.AddServersWizard.NextButtonInfo, new RecordItemIndex(8));
            repo.AddServersWizard.NextButton.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AddServersWizard.NextButton' at Center.", repo.AddServersWizard.NextButtonInfo, new RecordItemIndex(9));
            repo.AddServersWizard.NextButton.Click();
            Delay.Milliseconds(200);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
