///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace SQLDMTestAutomation
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The GlobeiconofabatchtypeSQLstatement recording.
    /// </summary>
    [TestModule("df70801f-8cae-4e95-8c11-a9662ea30c2f", ModuleType.Recording, 1)]
    public partial class GlobeiconofabatchtypeSQLstatement : ITestModule
    {
        /// <summary>
        /// Holds an instance of the SQLDMTestAutomationRepository repository.
        /// </summary>
        public static SQLDMTestAutomationRepository repo = SQLDMTestAutomationRepository.Instance;

        static GlobeiconofabatchtypeSQLstatement instance = new GlobeiconofabatchtypeSQLstatement();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public GlobeiconofabatchtypeSQLstatement()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static GlobeiconofabatchtypeSQLstatement Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.2")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.2")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(0));
            Delay.Duration(1000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Move item 'MonitoredSqlServerInstancePropertiesDial.QueryMonitor' at Center.", repo.MonitoredSqlServerInstancePropertiesDial.QueryMonitorInfo, new RecordItemIndex(1));
            repo.MonitoredSqlServerInstancePropertiesDial.QueryMonitor.MoveTo();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MonitoredSqlServerInstancePropertiesDial.QueryMonitor' at Center.", repo.MonitoredSqlServerInstancePropertiesDial.QueryMonitorInfo, new RecordItemIndex(2));
            repo.MonitoredSqlServerInstancePropertiesDial.QueryMonitor.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Move item 'MonitoredSqlServerInstancePropertiesDial.EnableQueryMonitorTraceCheckBox' at Center.", repo.MonitoredSqlServerInstancePropertiesDial.EnableQueryMonitorTraceCheckBoxInfo, new RecordItemIndex(3));
            repo.MonitoredSqlServerInstancePropertiesDial.EnableQueryMonitorTraceCheckBox.MoveTo();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MonitoredSqlServerInstancePropertiesDial.EnableQueryMonitorTraceCheckBox' at Center.", repo.MonitoredSqlServerInstancePropertiesDial.EnableQueryMonitorTraceCheckBoxInfo, new RecordItemIndex(4));
            repo.MonitoredSqlServerInstancePropertiesDial.EnableQueryMonitorTraceCheckBox.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Move item 'MonitoredSqlServerInstancePropertiesDial.TableLayoutPanel19.CollectActualQueryPlans' at Center.", repo.MonitoredSqlServerInstancePropertiesDial.TableLayoutPanel19.CollectActualQueryPlansInfo, new RecordItemIndex(5));
            repo.MonitoredSqlServerInstancePropertiesDial.TableLayoutPanel19.CollectActualQueryPlans.MoveTo();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Checked='false') on item 'MonitoredSqlServerInstancePropertiesDial.TableLayoutPanel19.CollectActualQueryPlans'.", repo.MonitoredSqlServerInstancePropertiesDial.TableLayoutPanel19.CollectActualQueryPlansInfo, new RecordItemIndex(6));
            Validate.AttributeEqual(repo.MonitoredSqlServerInstancePropertiesDial.TableLayoutPanel19.CollectActualQueryPlansInfo, "Checked", "false");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
