///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace SQLDMTestAutomation
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The ODEQPWithNoData recording.
    /// </summary>
    [TestModule("7854a627-cd46-40a0-b785-846a4eb1c33f", ModuleType.Recording, 1)]
    public partial class ODEQPWithNoData : ITestModule
    {
        /// <summary>
        /// Holds an instance of the SQLDMTestAutomationRepository repository.
        /// </summary>
        public static SQLDMTestAutomationRepository repo = SQLDMTestAutomationRepository.Instance;

        static ODEQPWithNoData instance = new ODEQPWithNoData();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public ODEQPWithNoData()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static ODEQPWithNoData Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.2")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.2")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Move item 'IderaSQLDiagnosticManagerSQLdmRepo.Server2005' at Center.", repo.IderaSQLDiagnosticManagerSQLdmRepo.Server2005Info, new RecordItemIndex(0));
            repo.IderaSQLDiagnosticManagerSQLdmRepo.Server2005.MoveTo();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Middle Click item 'IderaSQLDiagnosticManagerSQLdmRepo.Server2005' at Center.", repo.IderaSQLDiagnosticManagerSQLdmRepo.Server2005Info, new RecordItemIndex(1));
            repo.IderaSQLDiagnosticManagerSQLdmRepo.Server2005.Click(System.Windows.Forms.MouseButtons.Middle);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Right Click item 'IderaSQLDiagnosticManagerSQLdmRepo.Server2005' at Center.", repo.IderaSQLDiagnosticManagerSQLdmRepo.Server2005Info, new RecordItemIndex(2));
            repo.IderaSQLDiagnosticManagerSQLdmRepo.Server2005.Click(System.Windows.Forms.MouseButtons.Right);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Move item 'SQLdmDesktopClient.Properties' at Center.", repo.SQLdmDesktopClient.PropertiesInfo, new RecordItemIndex(3));
            repo.SQLdmDesktopClient.Properties.MoveTo();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SQLdmDesktopClient.Properties' at Center.", repo.SQLdmDesktopClient.PropertiesInfo, new RecordItemIndex(4));
            repo.SQLdmDesktopClient.Properties.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(5));
            Delay.Duration(1000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Move item 'MonitoredSqlServerInstancePropertiesDial.QueryMonitor' at Center.", repo.MonitoredSqlServerInstancePropertiesDial.QueryMonitorInfo, new RecordItemIndex(6));
            repo.MonitoredSqlServerInstancePropertiesDial.QueryMonitor.MoveTo();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MonitoredSqlServerInstancePropertiesDial.QueryMonitor' at Center.", repo.MonitoredSqlServerInstancePropertiesDial.QueryMonitorInfo, new RecordItemIndex(7));
            repo.MonitoredSqlServerInstancePropertiesDial.QueryMonitor.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Move item 'MonitoredSqlServerInstancePropertiesDial.EnableQueryMonitorTraceCheckBox' at Center.", repo.MonitoredSqlServerInstancePropertiesDial.EnableQueryMonitorTraceCheckBoxInfo, new RecordItemIndex(8));
            repo.MonitoredSqlServerInstancePropertiesDial.EnableQueryMonitorTraceCheckBox.MoveTo();
            Delay.Milliseconds(200);
            
            EnableQueryMonitor();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Move item 'MonitoredSqlServerInstancePropertiesDial.TableLayoutPanel19.CollectActualQueryPlans' at Center.", repo.MonitoredSqlServerInstancePropertiesDial.TableLayoutPanel19.CollectActualQueryPlansInfo, new RecordItemIndex(10));
            repo.MonitoredSqlServerInstancePropertiesDial.TableLayoutPanel19.CollectActualQueryPlans.MoveTo();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Checked='false') on item 'MonitoredSqlServerInstancePropertiesDial.TableLayoutPanel19.CollectActualQueryPlans'.", repo.MonitoredSqlServerInstancePropertiesDial.TableLayoutPanel19.CollectActualQueryPlansInfo, new RecordItemIndex(11));
            Validate.AttributeEqual(repo.MonitoredSqlServerInstancePropertiesDial.TableLayoutPanel19.CollectActualQueryPlansInfo, "Checked", "false");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Move item 'MonitoredSqlServerInstancePropertiesDial.PropertiesControl.Duration' at Center.", repo.MonitoredSqlServerInstancePropertiesDial.PropertiesControl.DurationInfo, new RecordItemIndex(12));
            repo.MonitoredSqlServerInstancePropertiesDial.PropertiesControl.Duration.MoveTo();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Ctrl+A' Press with focus on 'MonitoredSqlServerInstancePropertiesDial.PropertiesControl.Duration'.", repo.MonitoredSqlServerInstancePropertiesDial.PropertiesControl.DurationInfo, new RecordItemIndex(13));
            Keyboard.PrepareFocus(repo.MonitoredSqlServerInstancePropertiesDial.PropertiesControl.Duration);
            Keyboard.Press(System.Windows.Forms.Keys.A | System.Windows.Forms.Keys.Control, Keyboard.DefaultScanCode, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '0' with focus on 'MonitoredSqlServerInstancePropertiesDial.PropertiesControl.Duration'.", repo.MonitoredSqlServerInstancePropertiesDial.PropertiesControl.DurationInfo, new RecordItemIndex(14));
            repo.MonitoredSqlServerInstancePropertiesDial.PropertiesControl.Duration.PressKeys("0");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MonitoredSqlServerInstancePropertiesDial.SelectTop' at Center.", repo.MonitoredSqlServerInstancePropertiesDial.SelectTopInfo, new RecordItemIndex(15));
            repo.MonitoredSqlServerInstancePropertiesDial.SelectTop.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Ctrl+A' Press with focus on 'MonitoredSqlServerInstancePropertiesDial.SelectTop'.", repo.MonitoredSqlServerInstancePropertiesDial.SelectTopInfo, new RecordItemIndex(16));
            Keyboard.PrepareFocus(repo.MonitoredSqlServerInstancePropertiesDial.SelectTop);
            Keyboard.Press(System.Windows.Forms.Keys.A | System.Windows.Forms.Keys.Control, Keyboard.DefaultScanCode, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '200' with focus on 'MonitoredSqlServerInstancePropertiesDial.SelectTop'.", repo.MonitoredSqlServerInstancePropertiesDial.SelectTopInfo, new RecordItemIndex(17));
            repo.MonitoredSqlServerInstancePropertiesDial.SelectTop.PressKeys("200");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MonitoredSqlServerInstancePropertiesDial.OkButton' at Center.", repo.MonitoredSqlServerInstancePropertiesDial.OkButtonInfo, new RecordItemIndex(18));
            repo.MonitoredSqlServerInstancePropertiesDial.OkButton.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Move item 'MonitoredSqlServerInstancePropertiesDial.OkButton' at Center.", repo.MonitoredSqlServerInstancePropertiesDial.OkButtonInfo, new RecordItemIndex(19));
            repo.MonitoredSqlServerInstancePropertiesDial.OkButton.MoveTo();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MonitoredSqlServerInstancePropertiesDial.OkButton' at Center.", repo.MonitoredSqlServerInstancePropertiesDial.OkButtonInfo, new RecordItemIndex(20));
            repo.MonitoredSqlServerInstancePropertiesDial.OkButton.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Move item 'ExceptionMessageBoxForm.Yes' at Center.", repo.ExceptionMessageBoxForm.YesInfo, new RecordItemIndex(21));
            repo.ExceptionMessageBoxForm.Yes.MoveTo();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ExceptionMessageBoxForm.Yes' at Center.", repo.ExceptionMessageBoxForm.YesInfo, new RecordItemIndex(22));
            repo.ExceptionMessageBoxForm.Yes.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(23));
            Delay.Duration(1000, false);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
