///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace SQLDMTestAutomation
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the SQLDMTestAutomationRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.2")]
    [RepositoryFolder("fef44676-cf73-4211-820e-be7621cd7bfd")]
    public partial class SQLDMTestAutomationRepository : RepoGenBaseFolder
    {
        static SQLDMTestAutomationRepository instance = new SQLDMTestAutomationRepository();
        SQLDMTestAutomationRepositoryFolders.SQLDMFolder _sqldm;
        SQLDMTestAutomationRepositoryFolders.SSMSFolder _ssms;
        SQLDMTestAutomationRepositoryFolders.SQLdmDesktopClientAppFolder1 _sqldmdesktopclient;
        SQLDMTestAutomationRepositoryFolders.AdvancedQueryFilterConfigurationDialogAppFolder _advancedqueryfilterconfigurationdialog;

        /// <summary>
        /// Gets the singleton class instance representing the SQLDMTestAutomationRepository element repository.
        /// </summary>
        [RepositoryFolder("fef44676-cf73-4211-820e-be7621cd7bfd")]
        public static SQLDMTestAutomationRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public SQLDMTestAutomationRepository() 
            : base("SQLDMTestAutomationRepository", "/", null, 0, false, "fef44676-cf73-4211-820e-be7621cd7bfd", ".\\RepositoryImages\\SQLDMTestAutomationRepositoryfef44676.rximgres")
        {
            _sqldm = new SQLDMTestAutomationRepositoryFolders.SQLDMFolder(this);
            _ssms = new SQLDMTestAutomationRepositoryFolders.SSMSFolder(this);
            _sqldmdesktopclient = new SQLDMTestAutomationRepositoryFolders.SQLdmDesktopClientAppFolder1(this);
            _advancedqueryfilterconfigurationdialog = new SQLDMTestAutomationRepositoryFolders.AdvancedQueryFilterConfigurationDialogAppFolder(this);
        }

#region Variables

        string _ServerName = "";

        /// <summary>
        /// Gets or sets the value of variable ServerName.
        /// </summary>
        [TestVariable("1414cc25-97b1-4e47-ab61-5d306e2f14c6")]
        public string ServerName
        {
            get { return _ServerName; }
            set { _ServerName = value; }
        }

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("fef44676-cf73-4211-820e-be7621cd7bfd")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The SQLDM folder.
        /// </summary>
        [RepositoryFolder("c18fc3ad-e59f-453e-b34b-bd7d00dbbffd")]
        public virtual SQLDMTestAutomationRepositoryFolders.SQLDMFolder SQLDM
        {
            get { return _sqldm; }
        }

        /// <summary>
        /// The SSMS folder.
        /// </summary>
        [RepositoryFolder("e9bdc3c6-ab91-44e7-b4d8-1efd59f7a695")]
        public virtual SQLDMTestAutomationRepositoryFolders.SSMSFolder SSMS
        {
            get { return _ssms; }
        }

        /// <summary>
        /// The SQLdmDesktopClient folder.
        /// </summary>
        [RepositoryFolder("4c1d647f-8d7d-4547-8a99-8c82f5dfa9f9")]
        public virtual SQLDMTestAutomationRepositoryFolders.SQLdmDesktopClientAppFolder1 SQLdmDesktopClient
        {
            get { return _sqldmdesktopclient; }
        }

        /// <summary>
        /// The AdvancedQueryFilterConfigurationDialog folder.
        /// </summary>
        [RepositoryFolder("8b2d0136-c5dc-4603-8c1f-f9bcd885c13e")]
        public virtual SQLDMTestAutomationRepositoryFolders.AdvancedQueryFilterConfigurationDialogAppFolder AdvancedQueryFilterConfigurationDialog
        {
            get { return _advancedqueryfilterconfigurationdialog; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.2")]
    public partial class SQLDMTestAutomationRepositoryFolders
    {
        /// <summary>
        /// The SQLDMFolder folder.
        /// </summary>
        [RepositoryFolder("c18fc3ad-e59f-453e-b34b-bd7d00dbbffd")]
        public partial class SQLDMFolder : RepoGenBaseFolder
        {
            SQLDMTestAutomationRepositoryFolders.IderaSQLDiagnosticManagerSQLdmRepoAppFolder _iderasqldiagnosticmanagersqldmrepo;
            SQLDMTestAutomationRepositoryFolders.MonitoredSqlServerInstancePropertiesDialAppFolder _monitoredsqlserverinstancepropertiesdial;
            SQLDMTestAutomationRepositoryFolders.SQLdmDesktopClientAppFolder _sqldmdesktopclient;
            SQLDMTestAutomationRepositoryFolders.SomeContextMenuAppFolder _somecontextmenu;
            SQLDMTestAutomationRepositoryFolders.ManageServersDialogAppFolder _manageserversdialog;
            SQLDMTestAutomationRepositoryFolders.AddServersWizardAppFolder _addserverswizard;

            /// <summary>
            /// Creates a new SQLDM  folder.
            /// </summary>
            public SQLDMFolder(RepoGenBaseFolder parentFolder) :
                    base("SQLDM", "", parentFolder, 0, null, false, "c18fc3ad-e59f-453e-b34b-bd7d00dbbffd", "")
            {
                _iderasqldiagnosticmanagersqldmrepo = new SQLDMTestAutomationRepositoryFolders.IderaSQLDiagnosticManagerSQLdmRepoAppFolder(this);
                _monitoredsqlserverinstancepropertiesdial = new SQLDMTestAutomationRepositoryFolders.MonitoredSqlServerInstancePropertiesDialAppFolder(this);
                _sqldmdesktopclient = new SQLDMTestAutomationRepositoryFolders.SQLdmDesktopClientAppFolder(this);
                _somecontextmenu = new SQLDMTestAutomationRepositoryFolders.SomeContextMenuAppFolder(this);
                _manageserversdialog = new SQLDMTestAutomationRepositoryFolders.ManageServersDialogAppFolder(this);
                _addserverswizard = new SQLDMTestAutomationRepositoryFolders.AddServersWizardAppFolder(this);
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("c18fc3ad-e59f-453e-b34b-bd7d00dbbffd")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The IderaSQLDiagnosticManagerSQLdmRepo folder.
            /// </summary>
            [RepositoryFolder("b4fb3fbf-37f1-4ea8-8a05-407ab9741ac6")]
            public virtual SQLDMTestAutomationRepositoryFolders.IderaSQLDiagnosticManagerSQLdmRepoAppFolder IderaSQLDiagnosticManagerSQLdmRepo
            {
                get { return _iderasqldiagnosticmanagersqldmrepo; }
            }

            /// <summary>
            /// The MonitoredSqlServerInstancePropertiesDial folder.
            /// </summary>
            [RepositoryFolder("ca2ce607-39c3-44b6-924e-0fef773d1433")]
            public virtual SQLDMTestAutomationRepositoryFolders.MonitoredSqlServerInstancePropertiesDialAppFolder MonitoredSqlServerInstancePropertiesDial
            {
                get { return _monitoredsqlserverinstancepropertiesdial; }
            }

            /// <summary>
            /// The SQLdmDesktopClient folder.
            /// </summary>
            [RepositoryFolder("1ad6602d-ccb9-45a2-bf31-905c78fe286e")]
            public virtual SQLDMTestAutomationRepositoryFolders.SQLdmDesktopClientAppFolder SQLdmDesktopClient
            {
                get { return _sqldmdesktopclient; }
            }

            /// <summary>
            /// The SomeContextMenu folder.
            /// </summary>
            [RepositoryFolder("a629e7ef-f0f5-4d80-bcde-22fa5bb05055")]
            public virtual SQLDMTestAutomationRepositoryFolders.SomeContextMenuAppFolder SomeContextMenu
            {
                get { return _somecontextmenu; }
            }

            /// <summary>
            /// The ManageServersDialog folder.
            /// </summary>
            [RepositoryFolder("78a2c140-75a4-4223-a89b-21fe843b3cfa")]
            public virtual SQLDMTestAutomationRepositoryFolders.ManageServersDialogAppFolder ManageServersDialog
            {
                get { return _manageserversdialog; }
            }

            /// <summary>
            /// The AddServersWizard folder.
            /// </summary>
            [RepositoryFolder("47244754-be09-4684-95c7-ea1fae2ca75b")]
            public virtual SQLDMTestAutomationRepositoryFolders.AddServersWizardAppFolder AddServersWizard
            {
                get { return _addserverswizard; }
            }
        }

        /// <summary>
        /// The IderaSQLDiagnosticManagerSQLdmRepoAppFolder folder.
        /// </summary>
        [RepositoryFolder("b4fb3fbf-37f1-4ea8-8a05-407ab9741ac6")]
        public partial class IderaSQLDiagnosticManagerSQLdmRepoAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _serverInfo;
            RepoItemInfo _server2017Info;
            RepoItemInfo _queriesInfo;
            RepoItemInfo _signaturemodeInfo;
            RepoItemInfo _configurequerymonitorInfo;
            RepoItemInfo _sqldmtodayInfo;
            RepoItemInfo _fileInfo;
            RepoItemInfo _allserversInfo;
            RepoItemInfo _allservers1Info;
            RepoItemInfo _win16x6402sql2017Info;
            RepoItemInfo _userviewtreeviewInfo;
            RepoItemInfo _querywaitstabInfo;
            RepoItemInfo _configuretabInfo;

            /// <summary>
            /// Creates a new IderaSQLDiagnosticManagerSQLdmRepo  folder.
            /// </summary>
            public IderaSQLDiagnosticManagerSQLdmRepoAppFolder(RepoGenBaseFolder parentFolder) :
                    base("IderaSQLDiagnosticManagerSQLdmRepo", "/form[@title~'^Idera\\ SQL\\ diagnostic\\ mana']", parentFolder, 30000, null, true, "b4fb3fbf-37f1-4ea8-8a05-407ab9741ac6", "")
            {
                _serverInfo = new RepoItemInfo(this, "Server", ".//container[@controlname='NavigationPaneControl']//container[@controlname='serverGroupPanel']/tree[@controlname='userViewTreeView']//treeitem[@accessiblename=$ServerName]", 30000, null, "82a5fa7d-86df-4386-9bd7-f49949e40f8c");
                _server2017Info = new RepoItemInfo(this, "Server2017", ".//container[@controlname='NavigationPaneControl']//container[@controlname='serverGroupPanel']/tree[@controlname='userViewTreeView']//treeitem[@accessiblename='WIN10SQL17']", 30000, null, "91a07a90-ff45-494a-aafc-f9ea7cf33825");
                _queriesInfo = new RepoItemInfo(this, "Queries", ".//toolbar[@automationid='ribbon']/tabpage[@automationid='Queries']/container[@automationid='tabItemText']/text[@caption='Queries']", 30000, null, "d2bb192f-687c-484a-a185-49989a0e9c96");
                _signaturemodeInfo = new RepoItemInfo(this, "SignatureMode", ".//toolbar[@automationid='ribbon']/tabpage[@automationid='Queries']/toolbar[@automationid='queriesTabViewsGroup']/container[@caption='']/radiobutton[1]", 30000, null, "08b3cbe5-42ce-445e-b40a-bcb102c74100");
                _configurequerymonitorInfo = new RepoItemInfo(this, "ConfigureQueryMonitor", ".//toolbar[@automationid='ribbon']/tabpage[@automationid='Queries']/toolbar[@automationid='queriesTabPropertiesGroup']/button", 30000, null, "7e4be6b1-77be-424f-a4b6-f25c97eedbd3");
                _sqldmtodayInfo = new RepoItemInfo(this, "SQLDMToday", ".//container[@automationid='viewContainer']/container[@automationid='windowsFormsHostControl']/?/?/container[@controlname='_child']//toolbar[@controlname='headerStrip']/text[@accessiblename='SQLDM Today']", 30000, null, "0a7c7718-a970-47cf-bbda-cba2e04e6f8a");
                _fileInfo = new RepoItemInfo(this, "File", ".//list[@automationid='fileMenu']/picture[@automationid='HeaderPresenter']/text[@caption='File']", 30000, null, "05f70e7c-9d06-44b4-ab0c-996f4ef92559");
                _allserversInfo = new RepoItemInfo(this, "AllServers", ".//container[@automationid='navigationPaneHost']//container[@controlname='NavigationPaneControl']//container[@controlname='serverGroupPanel']/tree[@controlname='userViewTreeView']//treeitem[@accessiblename='All Servers']", 30000, null, "987dd453-196c-49ff-9dc0-4b54ad5225b8");
                _allservers1Info = new RepoItemInfo(this, "AllServers1", ".//container[@automationid='navigationPaneHost']//container[@controlname='NavigationPaneControl']//container[@controlname='serverGroupPanel']/tree[@controlname='userViewTreeView']/tree[@accessiblerole='Outline']/treeitem[@accessiblename='All Servers']", 30000, null, "5b05942e-23c6-425e-a1b4-6c1bfdd2f8aa");
                _win16x6402sql2017Info = new RepoItemInfo(this, "WIN16X6402SQL2017", ".//container[@automationid='navigationPaneHost']//container[@controlname='NavigationPaneControl']//container[@controlname='serverGroupPanel']/tree[@controlname='userViewTreeView']//treeitem[@accessiblename='WIN16X64-02\\SQL2017']", 30000, null, "f90893f9-4e63-4341-8f43-3125514d2ba7");
                _userviewtreeviewInfo = new RepoItemInfo(this, "UserViewTreeView", "?/?/container[@automationid='navigationPaneHost']/?/?/container[@controlname='NavigationPaneControl']/?/?/container[@controlname='ultraExplorerBarContainerControl1']/?/?/container[@controlname='serverGroupPanel']/tree[@controlname='userViewTreeView']", 30000, null, "36ded65f-a0b2-45e9-bde0-7bc3ae732691");
                _querywaitstabInfo = new RepoItemInfo(this, "QueryWaitsTAB", ".//toolbar[@automationid='ribbon']/tabpage[@automationid='Queries']/toolbar[@automationid='queriesTabViewsGroup']/container[@caption='']/radiobutton[4]", 30000, null, "12a9f12a-1a22-4a3a-b2e1-3f56feb5082e");
                _configuretabInfo = new RepoItemInfo(this, "ConfigureTAB", ".//tabpage[@automationid='Queries']/toolbar[@automationid='actionsRibbonGroup']/button[2]", 30000, null, "0e44c7f3-5104-4bbb-9bd5-03a19da794bd");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("b4fb3fbf-37f1-4ea8-8a05-407ab9741ac6")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("b4fb3fbf-37f1-4ea8-8a05-407ab9741ac6")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Server item.
            /// </summary>
            [RepositoryItem("82a5fa7d-86df-4386-9bd7-f49949e40f8c")]
            public virtual Ranorex.TreeItem Server
            {
                get
                {
                    return _serverInfo.CreateAdapter<Ranorex.TreeItem>(true);
                }
            }

            /// <summary>
            /// The Server item info.
            /// </summary>
            [RepositoryItemInfo("82a5fa7d-86df-4386-9bd7-f49949e40f8c")]
            public virtual RepoItemInfo ServerInfo
            {
                get
                {
                    return _serverInfo;
                }
            }

            /// <summary>
            /// The Server2017 item.
            /// </summary>
            [RepositoryItem("91a07a90-ff45-494a-aafc-f9ea7cf33825")]
            public virtual Ranorex.TreeItem Server2017
            {
                get
                {
                    return _server2017Info.CreateAdapter<Ranorex.TreeItem>(true);
                }
            }

            /// <summary>
            /// The Server2017 item info.
            /// </summary>
            [RepositoryItemInfo("91a07a90-ff45-494a-aafc-f9ea7cf33825")]
            public virtual RepoItemInfo Server2017Info
            {
                get
                {
                    return _server2017Info;
                }
            }

            /// <summary>
            /// The Queries item.
            /// </summary>
            [RepositoryItem("d2bb192f-687c-484a-a185-49989a0e9c96")]
            public virtual Ranorex.Text Queries
            {
                get
                {
                    return _queriesInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Queries item info.
            /// </summary>
            [RepositoryItemInfo("d2bb192f-687c-484a-a185-49989a0e9c96")]
            public virtual RepoItemInfo QueriesInfo
            {
                get
                {
                    return _queriesInfo;
                }
            }

            /// <summary>
            /// The SignatureMode item.
            /// </summary>
            [RepositoryItem("08b3cbe5-42ce-445e-b40a-bcb102c74100")]
            public virtual Ranorex.RadioButton SignatureMode
            {
                get
                {
                    return _signaturemodeInfo.CreateAdapter<Ranorex.RadioButton>(true);
                }
            }

            /// <summary>
            /// The SignatureMode item info.
            /// </summary>
            [RepositoryItemInfo("08b3cbe5-42ce-445e-b40a-bcb102c74100")]
            public virtual RepoItemInfo SignatureModeInfo
            {
                get
                {
                    return _signaturemodeInfo;
                }
            }

            /// <summary>
            /// The ConfigureQueryMonitor item.
            /// </summary>
            [RepositoryItem("7e4be6b1-77be-424f-a4b6-f25c97eedbd3")]
            public virtual Ranorex.Button ConfigureQueryMonitor
            {
                get
                {
                    return _configurequerymonitorInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ConfigureQueryMonitor item info.
            /// </summary>
            [RepositoryItemInfo("7e4be6b1-77be-424f-a4b6-f25c97eedbd3")]
            public virtual RepoItemInfo ConfigureQueryMonitorInfo
            {
                get
                {
                    return _configurequerymonitorInfo;
                }
            }

            /// <summary>
            /// The SQLDMToday item.
            /// </summary>
            [RepositoryItem("0a7c7718-a970-47cf-bbda-cba2e04e6f8a")]
            public virtual Ranorex.Text SQLDMToday
            {
                get
                {
                    return _sqldmtodayInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The SQLDMToday item info.
            /// </summary>
            [RepositoryItemInfo("0a7c7718-a970-47cf-bbda-cba2e04e6f8a")]
            public virtual RepoItemInfo SQLDMTodayInfo
            {
                get
                {
                    return _sqldmtodayInfo;
                }
            }

            /// <summary>
            /// The File item.
            /// </summary>
            [RepositoryItem("05f70e7c-9d06-44b4-ab0c-996f4ef92559")]
            public virtual Ranorex.Text File
            {
                get
                {
                    return _fileInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The File item info.
            /// </summary>
            [RepositoryItemInfo("05f70e7c-9d06-44b4-ab0c-996f4ef92559")]
            public virtual RepoItemInfo FileInfo
            {
                get
                {
                    return _fileInfo;
                }
            }

            /// <summary>
            /// The AllServers item.
            /// </summary>
            [RepositoryItem("987dd453-196c-49ff-9dc0-4b54ad5225b8")]
            public virtual Ranorex.TreeItem AllServers
            {
                get
                {
                    return _allserversInfo.CreateAdapter<Ranorex.TreeItem>(true);
                }
            }

            /// <summary>
            /// The AllServers item info.
            /// </summary>
            [RepositoryItemInfo("987dd453-196c-49ff-9dc0-4b54ad5225b8")]
            public virtual RepoItemInfo AllServersInfo
            {
                get
                {
                    return _allserversInfo;
                }
            }

            /// <summary>
            /// The AllServers1 item.
            /// </summary>
            [RepositoryItem("5b05942e-23c6-425e-a1b4-6c1bfdd2f8aa")]
            public virtual Ranorex.TreeItem AllServers1
            {
                get
                {
                    return _allservers1Info.CreateAdapter<Ranorex.TreeItem>(true);
                }
            }

            /// <summary>
            /// The AllServers1 item info.
            /// </summary>
            [RepositoryItemInfo("5b05942e-23c6-425e-a1b4-6c1bfdd2f8aa")]
            public virtual RepoItemInfo AllServers1Info
            {
                get
                {
                    return _allservers1Info;
                }
            }

            /// <summary>
            /// The WIN16X6402SQL2017 item.
            /// </summary>
            [RepositoryItem("f90893f9-4e63-4341-8f43-3125514d2ba7")]
            public virtual Ranorex.TreeItem WIN16X6402SQL2017
            {
                get
                {
                    return _win16x6402sql2017Info.CreateAdapter<Ranorex.TreeItem>(true);
                }
            }

            /// <summary>
            /// The WIN16X6402SQL2017 item info.
            /// </summary>
            [RepositoryItemInfo("f90893f9-4e63-4341-8f43-3125514d2ba7")]
            public virtual RepoItemInfo WIN16X6402SQL2017Info
            {
                get
                {
                    return _win16x6402sql2017Info;
                }
            }

            /// <summary>
            /// The UserViewTreeView item.
            /// </summary>
            [RepositoryItem("36ded65f-a0b2-45e9-bde0-7bc3ae732691")]
            public virtual Ranorex.Tree UserViewTreeView
            {
                get
                {
                    return _userviewtreeviewInfo.CreateAdapter<Ranorex.Tree>(true);
                }
            }

            /// <summary>
            /// The UserViewTreeView item info.
            /// </summary>
            [RepositoryItemInfo("36ded65f-a0b2-45e9-bde0-7bc3ae732691")]
            public virtual RepoItemInfo UserViewTreeViewInfo
            {
                get
                {
                    return _userviewtreeviewInfo;
                }
            }

            /// <summary>
            /// The QueryWaitsTAB item.
            /// </summary>
            [RepositoryItem("12a9f12a-1a22-4a3a-b2e1-3f56feb5082e")]
            public virtual Ranorex.RadioButton QueryWaitsTAB
            {
                get
                {
                    return _querywaitstabInfo.CreateAdapter<Ranorex.RadioButton>(true);
                }
            }

            /// <summary>
            /// The QueryWaitsTAB item info.
            /// </summary>
            [RepositoryItemInfo("12a9f12a-1a22-4a3a-b2e1-3f56feb5082e")]
            public virtual RepoItemInfo QueryWaitsTABInfo
            {
                get
                {
                    return _querywaitstabInfo;
                }
            }

            /// <summary>
            /// The ConfigureTAB item.
            /// </summary>
            [RepositoryItem("0e44c7f3-5104-4bbb-9bd5-03a19da794bd")]
            public virtual Ranorex.Button ConfigureTAB
            {
                get
                {
                    return _configuretabInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ConfigureTAB item info.
            /// </summary>
            [RepositoryItemInfo("0e44c7f3-5104-4bbb-9bd5-03a19da794bd")]
            public virtual RepoItemInfo ConfigureTABInfo
            {
                get
                {
                    return _configuretabInfo;
                }
            }
        }

        /// <summary>
        /// The MonitoredSqlServerInstancePropertiesDialAppFolder folder.
        /// </summary>
        [RepositoryFolder("ca2ce607-39c3-44b6-924e-0fef773d1433")]
        public partial class MonitoredSqlServerInstancePropertiesDialAppFolder : RepoGenBaseFolder
        {
            SQLDMTestAutomationRepositoryFolders.TableLayoutPanel19Folder _tablelayoutpanel19;
            RepoItemInfo _enablequerymonitortracecheckboxInfo;
            RepoItemInfo _someindicatorInfo;
            RepoItemInfo _updowneditInfo;
            RepoItemInfo _comboboxInfo;
            RepoItemInfo _okbuttonInfo;
            RepoItemInfo _listitemInfo;
            RepoItemInfo _closeInfo;
            RepoItemInfo _chkcollectquerywaitsstatisticsInfo;
            RepoItemInfo _chkuseqsInfo;
            RepoItemInfo _querymillisecondsInfo;
            RepoItemInfo _advancedoptionsbuttonInfo;
            RepoItemInfo _waitmonitoringtabInfo;

            /// <summary>
            /// Creates a new MonitoredSqlServerInstancePropertiesDial  folder.
            /// </summary>
            public MonitoredSqlServerInstancePropertiesDialAppFolder(RepoGenBaseFolder parentFolder) :
                    base("MonitoredSqlServerInstancePropertiesDial", "/form[@controlname='MonitoredSqlServerInstancePropertiesDialog']", parentFolder, 30000, null, true, "ca2ce607-39c3-44b6-924e-0fef773d1433", "")
            {
                _tablelayoutpanel19 = new SQLDMTestAutomationRepositoryFolders.TableLayoutPanel19Folder(this);
                _enablequerymonitortracecheckboxInfo = new RepoItemInfo(this, "EnableQueryMonitorTraceCheckBox", "container[@controlname='propertiesControl']//container[@controlname='queryMonitorPropertyPage']//container[@controlname='tableLayoutPanel17']/checkbox[@controlname='enableQueryMonitorTraceCheckBox']", 30000, null, "c19e42bd-757e-41bc-9bda-4986a05f4d11");
                _someindicatorInfo = new RepoItemInfo(this, "SomeIndicator", "container[@controlname='propertiesControl']/?/?/container[@controlname='panel2']/container[@controlname='queryMonitorPropertyPage']//indicator", 30000, null, "30680a87-cdd0-4419-9dac-7e6c4395c1ad");
                _updowneditInfo = new RepoItemInfo(this, "UpDownEdit", "container[@controlname='propertiesControl']//container[@controlname='tableLayoutPanel16']/container[@controlname='fmePoorlyPerformingThresholds']//container[@controlname='topPlanTableLayoutPanel']/container[@controlname='topPlanSpinner']/text[@controlname='upDownEdit']", 30000, null, "270a3822-0209-436d-ae49-588334cdc551");
                _comboboxInfo = new RepoItemInfo(this, "ComboBox", "container[@controlname='propertiesControl']//container[@controlname='tableLayoutPanel16']/container[@controlname='fmePoorlyPerformingThresholds']/?/?/element[@controlname='topPlanComboBox']/combobox[@accessiblename='Plans by ']/combobox[@accessiblerole='ComboBox']", 30000, null, "dc5ee464-4a79-4cc9-8181-792c0936f114");
                _okbuttonInfo = new RepoItemInfo(this, "OkButton", "button[@controlname='okButton']", 30000, null, "a9de51d9-a3bf-4e60-9edc-68fd0f899217");
                _listitemInfo = new RepoItemInfo(this, "ListItem", "container[@controlname='propertiesControl']//list[@controlname='propertyPageListBox']//listitem[@index='2']", 30000, null, "b6de4d46-b632-483a-a92e-906aaba2138a");
                _closeInfo = new RepoItemInfo(this, "Close", ".//button[@accessiblename='Close']", 30000, null, "5c72cc6d-67da-4d27-90cc-fd25a0c1765f");
                _chkcollectquerywaitsstatisticsInfo = new RepoItemInfo(this, "ChkCollectQueryWaitsStatistics", "container[@controlname='propertiesControl']//container[@controlname='waitPropertyPage']//container[@controlname='collectStatisticsSecondaryContainer']/checkbox[@controlname='chkCollectActiveWaits']", 30000, null, "0ee1417e-9802-4049-a721-f1721a82ad63");
                _chkuseqsInfo = new RepoItemInfo(this, "ChkUseQs", "container[@controlname='propertiesControl']//container[@controlname='waitPropertyPage']//container[@controlname='collectStatisticsSecondaryContainer']/checkbox[@controlname='chkUseQs']", 30000, null, "af7177e1-0310-4f54-b7af-065fd80552f9");
                _querymillisecondsInfo = new RepoItemInfo(this, "QueryMilliseconds", "container[@controlname='propertiesControl']//container[@controlname='tableLayoutPanel16']/container[@controlname='fmePoorlyPerformingThresholds']/?/?/container[@controlname='durationThresholdSpinner']/text[@controlname='upDownEdit']", 30000, null, "bdc1f4f1-621d-4572-8927-4907172f7cb2");
                _advancedoptionsbuttonInfo = new RepoItemInfo(this, "AdvancedOptionsButton", "container[@controlname='propertiesControl']//container[@controlname='queryMonitorPropertyPage']/?/?/button[@controlname='queryMonitorAdvancedOptionsButton']", 30000, null, "5a798ce7-6804-4395-8875-e422537e15aa");
                _waitmonitoringtabInfo = new RepoItemInfo(this, "WaitMonitoringTAB", "container[@controlname='propertiesControl']//list[@controlname='propertyPageListBox']/?/?/listitem[@index='11']", 30000, null, "ad498492-c91d-4a29-a2de-c04208520b8b");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("ca2ce607-39c3-44b6-924e-0fef773d1433")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("ca2ce607-39c3-44b6-924e-0fef773d1433")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The EnableQueryMonitorTraceCheckBox item.
            /// </summary>
            [RepositoryItem("c19e42bd-757e-41bc-9bda-4986a05f4d11")]
            public virtual Ranorex.CheckBox EnableQueryMonitorTraceCheckBox
            {
                get
                {
                    return _enablequerymonitortracecheckboxInfo.CreateAdapter<Ranorex.CheckBox>(true);
                }
            }

            /// <summary>
            /// The EnableQueryMonitorTraceCheckBox item info.
            /// </summary>
            [RepositoryItemInfo("c19e42bd-757e-41bc-9bda-4986a05f4d11")]
            public virtual RepoItemInfo EnableQueryMonitorTraceCheckBoxInfo
            {
                get
                {
                    return _enablequerymonitortracecheckboxInfo;
                }
            }

            /// <summary>
            /// The SomeIndicator item.
            /// </summary>
            [RepositoryItem("30680a87-cdd0-4419-9dac-7e6c4395c1ad")]
            public virtual Ranorex.Indicator SomeIndicator
            {
                get
                {
                    return _someindicatorInfo.CreateAdapter<Ranorex.Indicator>(true);
                }
            }

            /// <summary>
            /// The SomeIndicator item info.
            /// </summary>
            [RepositoryItemInfo("30680a87-cdd0-4419-9dac-7e6c4395c1ad")]
            public virtual RepoItemInfo SomeIndicatorInfo
            {
                get
                {
                    return _someindicatorInfo;
                }
            }

            /// <summary>
            /// The UpDownEdit item.
            /// </summary>
            [RepositoryItem("270a3822-0209-436d-ae49-588334cdc551")]
            public virtual Ranorex.Text UpDownEdit
            {
                get
                {
                    return _updowneditInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The UpDownEdit item info.
            /// </summary>
            [RepositoryItemInfo("270a3822-0209-436d-ae49-588334cdc551")]
            public virtual RepoItemInfo UpDownEditInfo
            {
                get
                {
                    return _updowneditInfo;
                }
            }

            /// <summary>
            /// The ComboBox item.
            /// </summary>
            [RepositoryItem("dc5ee464-4a79-4cc9-8181-792c0936f114")]
            public virtual Ranorex.ComboBox ComboBox
            {
                get
                {
                    return _comboboxInfo.CreateAdapter<Ranorex.ComboBox>(true);
                }
            }

            /// <summary>
            /// The ComboBox item info.
            /// </summary>
            [RepositoryItemInfo("dc5ee464-4a79-4cc9-8181-792c0936f114")]
            public virtual RepoItemInfo ComboBoxInfo
            {
                get
                {
                    return _comboboxInfo;
                }
            }

            /// <summary>
            /// The OkButton item.
            /// </summary>
            [RepositoryItem("a9de51d9-a3bf-4e60-9edc-68fd0f899217")]
            public virtual Ranorex.Button OkButton
            {
                get
                {
                    return _okbuttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The OkButton item info.
            /// </summary>
            [RepositoryItemInfo("a9de51d9-a3bf-4e60-9edc-68fd0f899217")]
            public virtual RepoItemInfo OkButtonInfo
            {
                get
                {
                    return _okbuttonInfo;
                }
            }

            /// <summary>
            /// The ListItem item.
            /// </summary>
            [RepositoryItem("b6de4d46-b632-483a-a92e-906aaba2138a")]
            public virtual Ranorex.ListItem ListItem
            {
                get
                {
                    return _listitemInfo.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The ListItem item info.
            /// </summary>
            [RepositoryItemInfo("b6de4d46-b632-483a-a92e-906aaba2138a")]
            public virtual RepoItemInfo ListItemInfo
            {
                get
                {
                    return _listitemInfo;
                }
            }

            /// <summary>
            /// The Close item.
            /// </summary>
            [RepositoryItem("5c72cc6d-67da-4d27-90cc-fd25a0c1765f")]
            public virtual Ranorex.Button Close
            {
                get
                {
                    return _closeInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Close item info.
            /// </summary>
            [RepositoryItemInfo("5c72cc6d-67da-4d27-90cc-fd25a0c1765f")]
            public virtual RepoItemInfo CloseInfo
            {
                get
                {
                    return _closeInfo;
                }
            }

            /// <summary>
            /// The ChkCollectQueryWaitsStatistics item.
            /// </summary>
            [RepositoryItem("0ee1417e-9802-4049-a721-f1721a82ad63")]
            public virtual Ranorex.CheckBox ChkCollectQueryWaitsStatistics
            {
                get
                {
                    return _chkcollectquerywaitsstatisticsInfo.CreateAdapter<Ranorex.CheckBox>(true);
                }
            }

            /// <summary>
            /// The ChkCollectQueryWaitsStatistics item info.
            /// </summary>
            [RepositoryItemInfo("0ee1417e-9802-4049-a721-f1721a82ad63")]
            public virtual RepoItemInfo ChkCollectQueryWaitsStatisticsInfo
            {
                get
                {
                    return _chkcollectquerywaitsstatisticsInfo;
                }
            }

            /// <summary>
            /// The ChkUseQs item.
            /// </summary>
            [RepositoryItem("af7177e1-0310-4f54-b7af-065fd80552f9")]
            public virtual Ranorex.CheckBox ChkUseQs
            {
                get
                {
                    return _chkuseqsInfo.CreateAdapter<Ranorex.CheckBox>(true);
                }
            }

            /// <summary>
            /// The ChkUseQs item info.
            /// </summary>
            [RepositoryItemInfo("af7177e1-0310-4f54-b7af-065fd80552f9")]
            public virtual RepoItemInfo ChkUseQsInfo
            {
                get
                {
                    return _chkuseqsInfo;
                }
            }

            /// <summary>
            /// The QueryMilliseconds item.
            /// </summary>
            [RepositoryItem("bdc1f4f1-621d-4572-8927-4907172f7cb2")]
            public virtual Ranorex.Text QueryMilliseconds
            {
                get
                {
                    return _querymillisecondsInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The QueryMilliseconds item info.
            /// </summary>
            [RepositoryItemInfo("bdc1f4f1-621d-4572-8927-4907172f7cb2")]
            public virtual RepoItemInfo QueryMillisecondsInfo
            {
                get
                {
                    return _querymillisecondsInfo;
                }
            }

            /// <summary>
            /// The AdvancedOptionsButton item.
            /// </summary>
            [RepositoryItem("5a798ce7-6804-4395-8875-e422537e15aa")]
            public virtual Ranorex.Button AdvancedOptionsButton
            {
                get
                {
                    return _advancedoptionsbuttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The AdvancedOptionsButton item info.
            /// </summary>
            [RepositoryItemInfo("5a798ce7-6804-4395-8875-e422537e15aa")]
            public virtual RepoItemInfo AdvancedOptionsButtonInfo
            {
                get
                {
                    return _advancedoptionsbuttonInfo;
                }
            }

            /// <summary>
            /// The WaitMonitoringTAB item.
            /// </summary>
            [RepositoryItem("ad498492-c91d-4a29-a2de-c04208520b8b")]
            public virtual Ranorex.ListItem WaitMonitoringTAB
            {
                get
                {
                    return _waitmonitoringtabInfo.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The WaitMonitoringTAB item info.
            /// </summary>
            [RepositoryItemInfo("ad498492-c91d-4a29-a2de-c04208520b8b")]
            public virtual RepoItemInfo WaitMonitoringTABInfo
            {
                get
                {
                    return _waitmonitoringtabInfo;
                }
            }

            /// <summary>
            /// The TableLayoutPanel19 folder.
            /// </summary>
            [RepositoryFolder("579708fb-78d2-4af0-a9a6-29bb75132e22")]
            public virtual SQLDMTestAutomationRepositoryFolders.TableLayoutPanel19Folder TableLayoutPanel19
            {
                get { return _tablelayoutpanel19; }
            }
        }

        /// <summary>
        /// The TableLayoutPanel19Folder folder.
        /// </summary>
        [RepositoryFolder("579708fb-78d2-4af0-a9a6-29bb75132e22")]
        public partial class TableLayoutPanel19Folder : RepoGenBaseFolder
        {
            RepoItemInfo _chkcollectestimatedqueryplansInfo;
            RepoItemInfo _chkcollectqueryplansInfo;
            RepoItemInfo _rbuttonusetraceInfo;

            /// <summary>
            /// Creates a new TableLayoutPanel19  folder.
            /// </summary>
            public TableLayoutPanel19Folder(RepoGenBaseFolder parentFolder) :
                    base("TableLayoutPanel19", "container[@controlname='propertiesControl']//container[@controlname='queryMonitorPropertyPage']/?/?/container[@controlname='tableLayoutPanel19']", parentFolder, 30000, null, false, "579708fb-78d2-4af0-a9a6-29bb75132e22", "")
            {
                _chkcollectestimatedqueryplansInfo = new RepoItemInfo(this, "ChkCollectEstimatedQueryPlans", "checkbox[@controlname='chkCollectEstimatedQueryPlans']", 30000, null, "7c2076de-a198-46df-b1f7-46de12aef923");
                _chkcollectqueryplansInfo = new RepoItemInfo(this, "ChkCollectQueryPlans", "checkbox[@controlname='chkCollectQueryPlans']", 30000, null, "a15cd278-674f-424e-889c-e49392021203");
                _rbuttonusetraceInfo = new RepoItemInfo(this, "RButtonUseTrace", "radiobutton[@controlname='rButtonUseTrace']", 30000, null, "043f7ebd-efe5-49ac-a1da-41a31cc64ea8");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("579708fb-78d2-4af0-a9a6-29bb75132e22")]
            public virtual Ranorex.Container Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("579708fb-78d2-4af0-a9a6-29bb75132e22")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ChkCollectEstimatedQueryPlans item.
            /// </summary>
            [RepositoryItem("7c2076de-a198-46df-b1f7-46de12aef923")]
            public virtual Ranorex.CheckBox ChkCollectEstimatedQueryPlans
            {
                get
                {
                    return _chkcollectestimatedqueryplansInfo.CreateAdapter<Ranorex.CheckBox>(true);
                }
            }

            /// <summary>
            /// The ChkCollectEstimatedQueryPlans item info.
            /// </summary>
            [RepositoryItemInfo("7c2076de-a198-46df-b1f7-46de12aef923")]
            public virtual RepoItemInfo ChkCollectEstimatedQueryPlansInfo
            {
                get
                {
                    return _chkcollectestimatedqueryplansInfo;
                }
            }

            /// <summary>
            /// The ChkCollectQueryPlans item.
            /// </summary>
            [RepositoryItem("a15cd278-674f-424e-889c-e49392021203")]
            public virtual Ranorex.CheckBox ChkCollectQueryPlans
            {
                get
                {
                    return _chkcollectqueryplansInfo.CreateAdapter<Ranorex.CheckBox>(true);
                }
            }

            /// <summary>
            /// The ChkCollectQueryPlans item info.
            /// </summary>
            [RepositoryItemInfo("a15cd278-674f-424e-889c-e49392021203")]
            public virtual RepoItemInfo ChkCollectQueryPlansInfo
            {
                get
                {
                    return _chkcollectqueryplansInfo;
                }
            }

            /// <summary>
            /// The RButtonUseTrace item.
            /// </summary>
            [RepositoryItem("043f7ebd-efe5-49ac-a1da-41a31cc64ea8")]
            public virtual Ranorex.RadioButton RButtonUseTrace
            {
                get
                {
                    return _rbuttonusetraceInfo.CreateAdapter<Ranorex.RadioButton>(true);
                }
            }

            /// <summary>
            /// The RButtonUseTrace item info.
            /// </summary>
            [RepositoryItemInfo("043f7ebd-efe5-49ac-a1da-41a31cc64ea8")]
            public virtual RepoItemInfo RButtonUseTraceInfo
            {
                get
                {
                    return _rbuttonusetraceInfo;
                }
            }
        }

        /// <summary>
        /// The SQLdmDesktopClientAppFolder folder.
        /// </summary>
        [RepositoryFolder("1ad6602d-ccb9-45a2-bf31-905c78fe286e")]
        public partial class SQLdmDesktopClientAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _propertiesInfo;

            /// <summary>
            /// Creates a new SQLdmDesktopClient  folder.
            /// </summary>
            public SQLdmDesktopClientAppFolder(RepoGenBaseFolder parentFolder) :
                    base("SQLdmDesktopClient", "/contextmenu[@processname='SQLdmDesktopClient']", parentFolder, 30000, null, true, "1ad6602d-ccb9-45a2-bf31-905c78fe286e", "")
            {
                _propertiesInfo = new RepoItemInfo(this, "Properties", "menuitem[@accessiblename='Properties...']", 30000, null, "79d06457-8423-4731-b162-bb0035d235f5");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("1ad6602d-ccb9-45a2-bf31-905c78fe286e")]
            public virtual Ranorex.ContextMenu Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.ContextMenu>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("1ad6602d-ccb9-45a2-bf31-905c78fe286e")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Properties item.
            /// </summary>
            [RepositoryItem("79d06457-8423-4731-b162-bb0035d235f5")]
            public virtual Ranorex.MenuItem Properties
            {
                get
                {
                    return _propertiesInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The Properties item info.
            /// </summary>
            [RepositoryItemInfo("79d06457-8423-4731-b162-bb0035d235f5")]
            public virtual RepoItemInfo PropertiesInfo
            {
                get
                {
                    return _propertiesInfo;
                }
            }
        }

        /// <summary>
        /// The SomeContextMenuAppFolder folder.
        /// </summary>
        [RepositoryFolder("a629e7ef-f0f5-4d80-bcde-22fa5bb05055")]
        public partial class SomeContextMenuAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _manageserversInfo;
            RepoItemInfo _newqueryInfo;

            /// <summary>
            /// Creates a new SomeContextMenu  folder.
            /// </summary>
            public SomeContextMenuAppFolder(RepoGenBaseFolder parentFolder) :
                    base("SomeContextMenu", "/contextmenu", parentFolder, 30000, null, false, "a629e7ef-f0f5-4d80-bcde-22fa5bb05055", "")
            {
                _manageserversInfo = new RepoItemInfo(this, "ManageServers", "menuitem[@automationid='menuFileManageServers']//text[@caption='Manage Servers...']", 30000, null, "ced467c1-26c7-4b81-bf56-fe2819fab370");
                _newqueryInfo = new RepoItemInfo(this, "NewQuery", "menuitem[@accessiblename='New Query']", 30000, null, "80867e47-bb6a-4e7f-a650-0df62393526f");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("a629e7ef-f0f5-4d80-bcde-22fa5bb05055")]
            public virtual Ranorex.ContextMenu Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.ContextMenu>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("a629e7ef-f0f5-4d80-bcde-22fa5bb05055")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ManageServers item.
            /// </summary>
            [RepositoryItem("ced467c1-26c7-4b81-bf56-fe2819fab370")]
            public virtual Ranorex.Text ManageServers
            {
                get
                {
                    return _manageserversInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The ManageServers item info.
            /// </summary>
            [RepositoryItemInfo("ced467c1-26c7-4b81-bf56-fe2819fab370")]
            public virtual RepoItemInfo ManageServersInfo
            {
                get
                {
                    return _manageserversInfo;
                }
            }

            /// <summary>
            /// The NewQuery item.
            /// </summary>
            [RepositoryItem("80867e47-bb6a-4e7f-a650-0df62393526f")]
            public virtual Ranorex.MenuItem NewQuery
            {
                get
                {
                    return _newqueryInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The NewQuery item info.
            /// </summary>
            [RepositoryItemInfo("80867e47-bb6a-4e7f-a650-0df62393526f")]
            public virtual RepoItemInfo NewQueryInfo
            {
                get
                {
                    return _newqueryInfo;
                }
            }
        }

        /// <summary>
        /// The ManageServersDialogAppFolder folder.
        /// </summary>
        [RepositoryFolder("78a2c140-75a4-4223-a89b-21fe843b3cfa")]
        public partial class ManageServersDialogAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _addbuttonInfo;
            RepoItemInfo _cancelbuttonInfo;

            /// <summary>
            /// Creates a new ManageServersDialog  folder.
            /// </summary>
            public ManageServersDialogAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ManageServersDialog", "/form[@controlname='ManageServersDialog']", parentFolder, 30000, null, true, "78a2c140-75a4-4223-a89b-21fe843b3cfa", "")
            {
                _addbuttonInfo = new RepoItemInfo(this, "AddButton", "button[@controlname='addButton']", 30000, null, "0f0bc92e-84f3-4e7a-96e1-eb0d5c610ef5");
                _cancelbuttonInfo = new RepoItemInfo(this, "CancelButton", "button[@controlname='cancelButton']", 30000, null, "5d521699-a69e-4f9f-907f-276787f854bf");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("78a2c140-75a4-4223-a89b-21fe843b3cfa")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("78a2c140-75a4-4223-a89b-21fe843b3cfa")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The AddButton item.
            /// </summary>
            [RepositoryItem("0f0bc92e-84f3-4e7a-96e1-eb0d5c610ef5")]
            public virtual Ranorex.Button AddButton
            {
                get
                {
                    return _addbuttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The AddButton item info.
            /// </summary>
            [RepositoryItemInfo("0f0bc92e-84f3-4e7a-96e1-eb0d5c610ef5")]
            public virtual RepoItemInfo AddButtonInfo
            {
                get
                {
                    return _addbuttonInfo;
                }
            }

            /// <summary>
            /// The CancelButton item.
            /// </summary>
            [RepositoryItem("5d521699-a69e-4f9f-907f-276787f854bf")]
            public virtual Ranorex.Button CancelButton
            {
                get
                {
                    return _cancelbuttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The CancelButton item info.
            /// </summary>
            [RepositoryItemInfo("5d521699-a69e-4f9f-907f-276787f854bf")]
            public virtual RepoItemInfo CancelButtonInfo
            {
                get
                {
                    return _cancelbuttonInfo;
                }
            }
        }

        /// <summary>
        /// The AddServersWizardAppFolder folder.
        /// </summary>
        [RepositoryFolder("47244754-be09-4684-95c7-ea1fae2ca75b")]
        public partial class AddServersWizardAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _nextbuttonInfo;
            RepoItemInfo _textInfo;
            RepoItemInfo _enablequerymonitortracecheckboxInfo;
            RepoItemInfo _plansbyInfo;
            RepoItemInfo _cancelInfo;

            /// <summary>
            /// Creates a new AddServersWizard  folder.
            /// </summary>
            public AddServersWizardAppFolder(RepoGenBaseFolder parentFolder) :
                    base("AddServersWizard", "/form[@controlname='AddServersWizard']", parentFolder, 30000, null, true, "47244754-be09-4684-95c7-ea1fae2ca75b", "")
            {
                _nextbuttonInfo = new RepoItemInfo(this, "NextButton", "?/?/button[@controlname='xb0664f16ddb81b92']", 30000, null, "2c7b0c01-2557-489d-82be-bcdd1a4deb4d");
                _textInfo = new RepoItemInfo(this, "Text", ".//text[@controlname='adhocInstancesTextBox']/text[@accessiblerole='Text']", 30000, null, "f0327c10-63af-4042-a0b1-dc97a5ecffee");
                _enablequerymonitortracecheckboxInfo = new RepoItemInfo(this, "EnableQueryMonitorTraceCheckBox", ".//container[@controlname='featuresGroupBox']/checkbox[@controlname='enableQueryMonitorTraceCheckBox']", 30000, null, "343f62f3-1c7e-4797-a86f-7f69bc01046c");
                _plansbyInfo = new RepoItemInfo(this, "PlansBy", ".//container[@controlname='featuresGroupBox']/container[@controlname='groupBox5']//combobox[@accessiblename='Plans by ']/combobox[@accessiblerole='ComboBox']", 30000, null, "7c306c03-79c2-4df9-9238-e4c2a5591a2f");
                _cancelInfo = new RepoItemInfo(this, "Cancel", ".//button[@text='Cancel']", 30000, null, "38e6369c-3605-49a9-9495-2f41db881964");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("47244754-be09-4684-95c7-ea1fae2ca75b")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("47244754-be09-4684-95c7-ea1fae2ca75b")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The NextButton item.
            /// </summary>
            [RepositoryItem("2c7b0c01-2557-489d-82be-bcdd1a4deb4d")]
            public virtual Ranorex.Button NextButton
            {
                get
                {
                    return _nextbuttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The NextButton item info.
            /// </summary>
            [RepositoryItemInfo("2c7b0c01-2557-489d-82be-bcdd1a4deb4d")]
            public virtual RepoItemInfo NextButtonInfo
            {
                get
                {
                    return _nextbuttonInfo;
                }
            }

            /// <summary>
            /// The Text item.
            /// </summary>
            [RepositoryItem("f0327c10-63af-4042-a0b1-dc97a5ecffee")]
            public virtual Ranorex.Text Text
            {
                get
                {
                    return _textInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Text item info.
            /// </summary>
            [RepositoryItemInfo("f0327c10-63af-4042-a0b1-dc97a5ecffee")]
            public virtual RepoItemInfo TextInfo
            {
                get
                {
                    return _textInfo;
                }
            }

            /// <summary>
            /// The EnableQueryMonitorTraceCheckBox item.
            /// </summary>
            [RepositoryItem("343f62f3-1c7e-4797-a86f-7f69bc01046c")]
            public virtual Ranorex.CheckBox EnableQueryMonitorTraceCheckBox
            {
                get
                {
                    return _enablequerymonitortracecheckboxInfo.CreateAdapter<Ranorex.CheckBox>(true);
                }
            }

            /// <summary>
            /// The EnableQueryMonitorTraceCheckBox item info.
            /// </summary>
            [RepositoryItemInfo("343f62f3-1c7e-4797-a86f-7f69bc01046c")]
            public virtual RepoItemInfo EnableQueryMonitorTraceCheckBoxInfo
            {
                get
                {
                    return _enablequerymonitortracecheckboxInfo;
                }
            }

            /// <summary>
            /// The PlansBy item.
            /// </summary>
            [RepositoryItem("7c306c03-79c2-4df9-9238-e4c2a5591a2f")]
            public virtual Ranorex.ComboBox PlansBy
            {
                get
                {
                    return _plansbyInfo.CreateAdapter<Ranorex.ComboBox>(true);
                }
            }

            /// <summary>
            /// The PlansBy item info.
            /// </summary>
            [RepositoryItemInfo("7c306c03-79c2-4df9-9238-e4c2a5591a2f")]
            public virtual RepoItemInfo PlansByInfo
            {
                get
                {
                    return _plansbyInfo;
                }
            }

            /// <summary>
            /// The Cancel item.
            /// </summary>
            [RepositoryItem("38e6369c-3605-49a9-9495-2f41db881964")]
            public virtual Ranorex.Button Cancel
            {
                get
                {
                    return _cancelInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Cancel item info.
            /// </summary>
            [RepositoryItemInfo("38e6369c-3605-49a9-9495-2f41db881964")]
            public virtual RepoItemInfo CancelInfo
            {
                get
                {
                    return _cancelInfo;
                }
            }
        }

        /// <summary>
        /// The SSMSFolder folder.
        /// </summary>
        [RepositoryFolder("e9bdc3c6-ab91-44e7-b4d8-1efd59f7a695")]
        public partial class SSMSFolder : RepoGenBaseFolder
        {
            SQLDMTestAutomationRepositoryFolders.MicrosoftSQLServerManagementStudioAppFolder _microsoftsqlservermanagementstudio;
            SQLDMTestAutomationRepositoryFolders.ConnectionDialogAppFolder _connectiondialog;
            SQLDMTestAutomationRepositoryFolders.SSMS_SomeContextMenuAppFolder _ssms_somecontextmenu;
            SQLDMTestAutomationRepositoryFolders.OpenFileAppFolder _openfile;

            /// <summary>
            /// Creates a new SSMS  folder.
            /// </summary>
            public SSMSFolder(RepoGenBaseFolder parentFolder) :
                    base("SSMS", "", parentFolder, 0, null, false, "e9bdc3c6-ab91-44e7-b4d8-1efd59f7a695", "")
            {
                _microsoftsqlservermanagementstudio = new SQLDMTestAutomationRepositoryFolders.MicrosoftSQLServerManagementStudioAppFolder(this);
                _connectiondialog = new SQLDMTestAutomationRepositoryFolders.ConnectionDialogAppFolder(this);
                _ssms_somecontextmenu = new SQLDMTestAutomationRepositoryFolders.SSMS_SomeContextMenuAppFolder(this);
                _openfile = new SQLDMTestAutomationRepositoryFolders.OpenFileAppFolder(this);
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("e9bdc3c6-ab91-44e7-b4d8-1efd59f7a695")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The MicrosoftSQLServerManagementStudio folder.
            /// </summary>
            [RepositoryFolder("8a3f136c-f885-4fbf-8158-6d98b48b02b1")]
            public virtual SQLDMTestAutomationRepositoryFolders.MicrosoftSQLServerManagementStudioAppFolder MicrosoftSQLServerManagementStudio
            {
                get { return _microsoftsqlservermanagementstudio; }
            }

            /// <summary>
            /// The ConnectionDialog folder.
            /// </summary>
            [RepositoryFolder("7ff60cdc-ea07-45cd-9e7d-95d395854b2f")]
            public virtual SQLDMTestAutomationRepositoryFolders.ConnectionDialogAppFolder ConnectionDialog
            {
                get { return _connectiondialog; }
            }

            /// <summary>
            /// The SSMS_SomeContextMenu folder.
            /// </summary>
            [RepositoryFolder("4c624302-bbd7-4410-99d9-315ecb6846f1")]
            public virtual SQLDMTestAutomationRepositoryFolders.SSMS_SomeContextMenuAppFolder SSMS_SomeContextMenu
            {
                get { return _ssms_somecontextmenu; }
            }

            /// <summary>
            /// The OpenFile folder.
            /// </summary>
            [RepositoryFolder("ebbf3da2-570f-4022-a3d1-45d2a3748652")]
            public virtual SQLDMTestAutomationRepositoryFolders.OpenFileAppFolder OpenFile
            {
                get { return _openfile; }
            }
        }

        /// <summary>
        /// The MicrosoftSQLServerManagementStudioAppFolder folder.
        /// </summary>
        [RepositoryFolder("8a3f136c-f885-4fbf-8158-6d98b48b02b1")]
        public partial class MicrosoftSQLServerManagementStudioAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _connectobjectexplorerInfo;
            RepoItemInfo _servervisibleinleftpaneInfo;
            RepoItemInfo _databasesInfo;
            RepoItemInfo _sqldmrepositoryInfo;
            RepoItemInfo _queryeditorInfo;
            RepoItemInfo _executeInfo;
            RepoItemInfo _tablecol_querymonitortopplancountfilterInfo;
            RepoItemInfo _tablecol_querymonitortopplancategoryfilterInfo;
            RepoItemInfo _tablecol_querymonitorquerystoremonitoringenabledInfo;
            RepoItemInfo _buttonnoInfo;

            /// <summary>
            /// Creates a new MicrosoftSQLServerManagementStudio  folder.
            /// </summary>
            public MicrosoftSQLServerManagementStudioAppFolder(RepoGenBaseFolder parentFolder) :
                    base("MicrosoftSQLServerManagementStudio", "/form[@title~'^Microsoft\\ SQL\\ Server\\ Mana']", parentFolder, 30000, null, true, "8a3f136c-f885-4fbf-8158-6d98b48b02b1", "")
            {
                _connectobjectexplorerInfo = new RepoItemInfo(this, "ConnectObjectExplorer", "container[@caption='Object Explorer']//toolbar[@accessiblename~'^SQL Server Object Explore']/button[@accessiblename~'^Connect Object Explorer']", 30000, null, "a509d2cc-2e14-4437-a0ab-5fec2a083977");
                _servervisibleinleftpaneInfo = new RepoItemInfo(this, "ServerVisibleInLeftPane", ".//tree[@controlname='ObjectExplorerTree']/tree[@accessiblename='Object Explorer Hierarchy']/treeitem[@accessiblename~'^'+$ServerName]", 30000, null, "7b2de711-8301-4d15-a1f5-7069dbf81450");
                _databasesInfo = new RepoItemInfo(this, "Databases", ".//tree[@controlname='ObjectExplorerTree']/tree[@accessiblename='Object Explorer Hierarchy']/treeitem[@accessiblename='Databases']", 30000, null, "746f725a-4fa6-4763-8f3d-4ce10db5d557");
                _sqldmrepositoryInfo = new RepoItemInfo(this, "SQLdmRepository", ".//tree[@controlname='ObjectExplorerTree']/tree[@accessiblename='Object Explorer Hierarchy']/treeitem[@accessiblename='SQLdmRepository']", 30000, null, "cd96dc4f-9177-4391-9543-678d196a959d");
                _queryeditorInfo = new RepoItemInfo(this, "QueryEditor", ".//element[@controlname='m_Editor']//text[@accessiblename~'^SQLQuery']/text[@accessiblename='selected text']", 30000, null, "dcfdc283-6c39-4efa-87ec-ad57e0aafed1");
                _executeInfo = new RepoItemInfo(this, "Execute", ".//toolbar[@accessiblename='SQL Editor']/button[@accessiblename='Execute']", 30000, null, "5e7cdb49-8b84-4fdf-9734-bb214f28ecc6");
                _tablecol_querymonitortopplancountfilterInfo = new RepoItemInfo(this, "TableCol_QueryMonitorTopPlanCountFilter", ".//table[@accessiblename='GridControl']//cell[@accessiblevalue='QueryMonitorTopPlanCountFilter']", 30000, null, "7779030f-15e2-470f-8e98-cf5b7a206482");
                _tablecol_querymonitortopplancategoryfilterInfo = new RepoItemInfo(this, "TableCol_QueryMonitorTopPlanCategoryFilter", ".//table[@accessiblename='GridControl']//cell[@accessiblevalue='QueryMonitorTopPlanCategoryFilter']", 30000, null, "14835a35-3776-4dbb-8f7b-efa70f385dce");
                _tablecol_querymonitorquerystoremonitoringenabledInfo = new RepoItemInfo(this, "TableCol_QueryMonitorQueryStoreMonitoringEnabled", ".//table[@accessiblename='GridControl']//cell[@accessiblevalue='QueryMonitorQueryStoreMonitoringEnabled']", 30000, null, "6ac8f383-255b-485e-bd9a-f772a8e609f4");
                _buttonnoInfo = new RepoItemInfo(this, "ButtonNo", "button[@text='&No']", 30000, null, "5b1e617a-a8ff-485f-bf70-14f7b02c0b09");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("8a3f136c-f885-4fbf-8158-6d98b48b02b1")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("8a3f136c-f885-4fbf-8158-6d98b48b02b1")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ConnectObjectExplorer item.
            /// </summary>
            [RepositoryItem("a509d2cc-2e14-4437-a0ab-5fec2a083977")]
            public virtual Ranorex.Button ConnectObjectExplorer
            {
                get
                {
                    return _connectobjectexplorerInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ConnectObjectExplorer item info.
            /// </summary>
            [RepositoryItemInfo("a509d2cc-2e14-4437-a0ab-5fec2a083977")]
            public virtual RepoItemInfo ConnectObjectExplorerInfo
            {
                get
                {
                    return _connectobjectexplorerInfo;
                }
            }

            /// <summary>
            /// The ServerVisibleInLeftPane item.
            /// </summary>
            [RepositoryItem("7b2de711-8301-4d15-a1f5-7069dbf81450")]
            public virtual Ranorex.TreeItem ServerVisibleInLeftPane
            {
                get
                {
                    return _servervisibleinleftpaneInfo.CreateAdapter<Ranorex.TreeItem>(true);
                }
            }

            /// <summary>
            /// The ServerVisibleInLeftPane item info.
            /// </summary>
            [RepositoryItemInfo("7b2de711-8301-4d15-a1f5-7069dbf81450")]
            public virtual RepoItemInfo ServerVisibleInLeftPaneInfo
            {
                get
                {
                    return _servervisibleinleftpaneInfo;
                }
            }

            /// <summary>
            /// The Databases item.
            /// </summary>
            [RepositoryItem("746f725a-4fa6-4763-8f3d-4ce10db5d557")]
            public virtual Ranorex.TreeItem Databases
            {
                get
                {
                    return _databasesInfo.CreateAdapter<Ranorex.TreeItem>(true);
                }
            }

            /// <summary>
            /// The Databases item info.
            /// </summary>
            [RepositoryItemInfo("746f725a-4fa6-4763-8f3d-4ce10db5d557")]
            public virtual RepoItemInfo DatabasesInfo
            {
                get
                {
                    return _databasesInfo;
                }
            }

            /// <summary>
            /// The SQLdmRepository item.
            /// </summary>
            [RepositoryItem("cd96dc4f-9177-4391-9543-678d196a959d")]
            public virtual Ranorex.TreeItem SQLdmRepository
            {
                get
                {
                    return _sqldmrepositoryInfo.CreateAdapter<Ranorex.TreeItem>(true);
                }
            }

            /// <summary>
            /// The SQLdmRepository item info.
            /// </summary>
            [RepositoryItemInfo("cd96dc4f-9177-4391-9543-678d196a959d")]
            public virtual RepoItemInfo SQLdmRepositoryInfo
            {
                get
                {
                    return _sqldmrepositoryInfo;
                }
            }

            /// <summary>
            /// The QueryEditor item.
            /// </summary>
            [RepositoryItem("dcfdc283-6c39-4efa-87ec-ad57e0aafed1")]
            public virtual Ranorex.Text QueryEditor
            {
                get
                {
                    return _queryeditorInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The QueryEditor item info.
            /// </summary>
            [RepositoryItemInfo("dcfdc283-6c39-4efa-87ec-ad57e0aafed1")]
            public virtual RepoItemInfo QueryEditorInfo
            {
                get
                {
                    return _queryeditorInfo;
                }
            }

            /// <summary>
            /// The Execute item.
            /// </summary>
            [RepositoryItem("5e7cdb49-8b84-4fdf-9734-bb214f28ecc6")]
            public virtual Ranorex.Button Execute
            {
                get
                {
                    return _executeInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Execute item info.
            /// </summary>
            [RepositoryItemInfo("5e7cdb49-8b84-4fdf-9734-bb214f28ecc6")]
            public virtual RepoItemInfo ExecuteInfo
            {
                get
                {
                    return _executeInfo;
                }
            }

            /// <summary>
            /// The TableCol_QueryMonitorTopPlanCountFilter item.
            /// </summary>
            [RepositoryItem("7779030f-15e2-470f-8e98-cf5b7a206482")]
            public virtual Ranorex.Cell TableCol_QueryMonitorTopPlanCountFilter
            {
                get
                {
                    return _tablecol_querymonitortopplancountfilterInfo.CreateAdapter<Ranorex.Cell>(true);
                }
            }

            /// <summary>
            /// The TableCol_QueryMonitorTopPlanCountFilter item info.
            /// </summary>
            [RepositoryItemInfo("7779030f-15e2-470f-8e98-cf5b7a206482")]
            public virtual RepoItemInfo TableCol_QueryMonitorTopPlanCountFilterInfo
            {
                get
                {
                    return _tablecol_querymonitortopplancountfilterInfo;
                }
            }

            /// <summary>
            /// The TableCol_QueryMonitorTopPlanCategoryFilter item.
            /// </summary>
            [RepositoryItem("14835a35-3776-4dbb-8f7b-efa70f385dce")]
            public virtual Ranorex.Cell TableCol_QueryMonitorTopPlanCategoryFilter
            {
                get
                {
                    return _tablecol_querymonitortopplancategoryfilterInfo.CreateAdapter<Ranorex.Cell>(true);
                }
            }

            /// <summary>
            /// The TableCol_QueryMonitorTopPlanCategoryFilter item info.
            /// </summary>
            [RepositoryItemInfo("14835a35-3776-4dbb-8f7b-efa70f385dce")]
            public virtual RepoItemInfo TableCol_QueryMonitorTopPlanCategoryFilterInfo
            {
                get
                {
                    return _tablecol_querymonitortopplancategoryfilterInfo;
                }
            }

            /// <summary>
            /// The TableCol_QueryMonitorQueryStoreMonitoringEnabled item.
            /// </summary>
            [RepositoryItem("6ac8f383-255b-485e-bd9a-f772a8e609f4")]
            public virtual Ranorex.Cell TableCol_QueryMonitorQueryStoreMonitoringEnabled
            {
                get
                {
                    return _tablecol_querymonitorquerystoremonitoringenabledInfo.CreateAdapter<Ranorex.Cell>(true);
                }
            }

            /// <summary>
            /// The TableCol_QueryMonitorQueryStoreMonitoringEnabled item info.
            /// </summary>
            [RepositoryItemInfo("6ac8f383-255b-485e-bd9a-f772a8e609f4")]
            public virtual RepoItemInfo TableCol_QueryMonitorQueryStoreMonitoringEnabledInfo
            {
                get
                {
                    return _tablecol_querymonitorquerystoremonitoringenabledInfo;
                }
            }

            /// <summary>
            /// The ButtonNo item.
            /// </summary>
            [RepositoryItem("5b1e617a-a8ff-485f-bf70-14f7b02c0b09")]
            public virtual Ranorex.Button ButtonNo
            {
                get
                {
                    return _buttonnoInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonNo item info.
            /// </summary>
            [RepositoryItemInfo("5b1e617a-a8ff-485f-bf70-14f7b02c0b09")]
            public virtual RepoItemInfo ButtonNoInfo
            {
                get
                {
                    return _buttonnoInfo;
                }
            }
        }

        /// <summary>
        /// The ConnectionDialogAppFolder folder.
        /// </summary>
        [RepositoryFolder("7ff60cdc-ea07-45cd-9e7d-95d395854b2f")]
        public partial class ConnectionDialogAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _servernametoconnectInfo;
            RepoItemInfo _connectInfo;

            /// <summary>
            /// Creates a new ConnectionDialog  folder.
            /// </summary>
            public ConnectionDialogAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ConnectionDialog", "/form[@controlname='ConnectionDialog']", parentFolder, 30000, null, true, "7ff60cdc-ea07-45cd-9e7d-95d395854b2f", "")
            {
                _servernametoconnectInfo = new RepoItemInfo(this, "ServerNameToConnect", "container[@controlname='simpleView']//combobox[@controlname='serverInstance']/text[@controlid='1001']", 30000, null, "bdb8cf99-253b-4bed-9e1e-8c49e16c6b98");
                _connectInfo = new RepoItemInfo(this, "Connect", "button[@controlname='connect']", 30000, null, "84f883f4-0a94-43e5-9621-549bfa6c2a53");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("7ff60cdc-ea07-45cd-9e7d-95d395854b2f")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("7ff60cdc-ea07-45cd-9e7d-95d395854b2f")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ServerNameToConnect item.
            /// </summary>
            [RepositoryItem("bdb8cf99-253b-4bed-9e1e-8c49e16c6b98")]
            public virtual Ranorex.Text ServerNameToConnect
            {
                get
                {
                    return _servernametoconnectInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The ServerNameToConnect item info.
            /// </summary>
            [RepositoryItemInfo("bdb8cf99-253b-4bed-9e1e-8c49e16c6b98")]
            public virtual RepoItemInfo ServerNameToConnectInfo
            {
                get
                {
                    return _servernametoconnectInfo;
                }
            }

            /// <summary>
            /// The Connect item.
            /// </summary>
            [RepositoryItem("84f883f4-0a94-43e5-9621-549bfa6c2a53")]
            public virtual Ranorex.Button Connect
            {
                get
                {
                    return _connectInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Connect item info.
            /// </summary>
            [RepositoryItemInfo("84f883f4-0a94-43e5-9621-549bfa6c2a53")]
            public virtual RepoItemInfo ConnectInfo
            {
                get
                {
                    return _connectInfo;
                }
            }
        }

        /// <summary>
        /// The SSMS_SomeContextMenuAppFolder folder.
        /// </summary>
        [RepositoryFolder("4c624302-bbd7-4410-99d9-315ecb6846f1")]
        public partial class SSMS_SomeContextMenuAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _newqueryInfo;

            /// <summary>
            /// Creates a new SSMS_SomeContextMenu  folder.
            /// </summary>
            public SSMS_SomeContextMenuAppFolder(RepoGenBaseFolder parentFolder) :
                    base("SSMS_SomeContextMenu", "/contextmenu", parentFolder, 30000, null, false, "4c624302-bbd7-4410-99d9-315ecb6846f1", "")
            {
                _newqueryInfo = new RepoItemInfo(this, "NewQuery", "menuitem[@accessiblename='New Query']", 30000, null, "ff47523b-e7de-49c9-b9c3-263184afb650");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("4c624302-bbd7-4410-99d9-315ecb6846f1")]
            public virtual Ranorex.ContextMenu Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.ContextMenu>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("4c624302-bbd7-4410-99d9-315ecb6846f1")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The NewQuery item.
            /// </summary>
            [RepositoryItem("ff47523b-e7de-49c9-b9c3-263184afb650")]
            public virtual Ranorex.MenuItem NewQuery
            {
                get
                {
                    return _newqueryInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The NewQuery item info.
            /// </summary>
            [RepositoryItemInfo("ff47523b-e7de-49c9-b9c3-263184afb650")]
            public virtual RepoItemInfo NewQueryInfo
            {
                get
                {
                    return _newqueryInfo;
                }
            }
        }

        /// <summary>
        /// The OpenFileAppFolder folder.
        /// </summary>
        [RepositoryFolder("ebbf3da2-570f-4022-a3d1-45d2a3748652")]
        public partial class OpenFileAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _text51Info;
            RepoItemInfo _openInfo;

            /// <summary>
            /// Creates a new OpenFile  folder.
            /// </summary>
            public OpenFileAppFolder(RepoGenBaseFolder parentFolder) :
                    base("OpenFile", "/form[@title='Open File']", parentFolder, 30000, null, true, "ebbf3da2-570f-4022-a3d1-45d2a3748652", "")
            {
                _text51Info = new RepoItemInfo(this, "Text51", "text[@controlid='51']", 30000, null, "1df7a31b-3a3b-41bc-8c6c-f2830c044256");
                _openInfo = new RepoItemInfo(this, "Open", "button[@accessiblename='Open']", 30000, null, "2cb41444-4cfa-44cd-9809-835bf0e01ca7");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("ebbf3da2-570f-4022-a3d1-45d2a3748652")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("ebbf3da2-570f-4022-a3d1-45d2a3748652")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Text51 item.
            /// </summary>
            [RepositoryItem("1df7a31b-3a3b-41bc-8c6c-f2830c044256")]
            public virtual Ranorex.Text Text51
            {
                get
                {
                    return _text51Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Text51 item info.
            /// </summary>
            [RepositoryItemInfo("1df7a31b-3a3b-41bc-8c6c-f2830c044256")]
            public virtual RepoItemInfo Text51Info
            {
                get
                {
                    return _text51Info;
                }
            }

            /// <summary>
            /// The Open item.
            /// </summary>
            [RepositoryItem("2cb41444-4cfa-44cd-9809-835bf0e01ca7")]
            public virtual Ranorex.Button Open
            {
                get
                {
                    return _openInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Open item info.
            /// </summary>
            [RepositoryItemInfo("2cb41444-4cfa-44cd-9809-835bf0e01ca7")]
            public virtual RepoItemInfo OpenInfo
            {
                get
                {
                    return _openInfo;
                }
            }
        }

        /// <summary>
        /// The SQLdmDesktopClientAppFolder1 folder.
        /// </summary>
        [RepositoryFolder("4c1d647f-8d7d-4547-8a99-8c82f5dfa9f9")]
        public partial class SQLdmDesktopClientAppFolder1 : RepoGenBaseFolder
        {
            RepoItemInfo _querymonitorleftpaneInfo;

            /// <summary>
            /// Creates a new SQLdmDesktopClient  folder.
            /// </summary>
            public SQLdmDesktopClientAppFolder1(RepoGenBaseFolder parentFolder) :
                    base("SQLdmDesktopClient", "/form[@controltypename='MonitoredSqlServerInstancePropertiesDialog']", parentFolder, 30000, null, true, "4c1d647f-8d7d-4547-8a99-8c82f5dfa9f9", "")
            {
                _querymonitorleftpaneInfo = new RepoItemInfo(this, "QueryMonitorLeftPane", "container[@controlname='propertiesControl']//list[@controlname='propertyPageListBox']/?/?/listitem[@index='2']", 30000, null, "af2dee37-fc4c-482b-96b6-5fed2013f92a");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("4c1d647f-8d7d-4547-8a99-8c82f5dfa9f9")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("4c1d647f-8d7d-4547-8a99-8c82f5dfa9f9")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The QueryMonitorLeftPane item.
            /// </summary>
            [RepositoryItem("af2dee37-fc4c-482b-96b6-5fed2013f92a")]
            public virtual Ranorex.ListItem QueryMonitorLeftPane
            {
                get
                {
                    return _querymonitorleftpaneInfo.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The QueryMonitorLeftPane item info.
            /// </summary>
            [RepositoryItemInfo("af2dee37-fc4c-482b-96b6-5fed2013f92a")]
            public virtual RepoItemInfo QueryMonitorLeftPaneInfo
            {
                get
                {
                    return _querymonitorleftpaneInfo;
                }
            }
        }

        /// <summary>
        /// The AdvancedQueryFilterConfigurationDialogAppFolder folder.
        /// </summary>
        [RepositoryFolder("8b2d0136-c5dc-4603-8c1f-f9bcd885c13e")]
        public partial class AdvancedQueryFilterConfigurationDialogAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _chkexcludedmInfo;
            RepoItemInfo _okbuttonInfo;

            /// <summary>
            /// Creates a new AdvancedQueryFilterConfigurationDialog  folder.
            /// </summary>
            public AdvancedQueryFilterConfigurationDialogAppFolder(RepoGenBaseFolder parentFolder) :
                    base("AdvancedQueryFilterConfigurationDialog", "/form[@controlname='AdvancedQueryFilterConfigurationDialog']", parentFolder, 30000, null, true, "8b2d0136-c5dc-4603-8c1f-f9bcd885c13e", "")
            {
                _chkexcludedmInfo = new RepoItemInfo(this, "ChkExcludeDM", "container[@controlname='propertiesControl1']//container[@controlname='propertyPage1']/container[@controlname='office2007PropertyPage1']//container[@controlname='panel1']/checkbox[@controlname='chkExcludeDM']", 30000, null, "0fdbe99b-02e6-443e-a166-6a8b08015f3d");
                _okbuttonInfo = new RepoItemInfo(this, "OkButton", "button[@controlname='okButton']", 30000, null, "80d20184-bca7-45f9-abfd-174fe18edd31");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("8b2d0136-c5dc-4603-8c1f-f9bcd885c13e")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("8b2d0136-c5dc-4603-8c1f-f9bcd885c13e")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ChkExcludeDM item.
            /// </summary>
            [RepositoryItem("0fdbe99b-02e6-443e-a166-6a8b08015f3d")]
            public virtual Ranorex.CheckBox ChkExcludeDM
            {
                get
                {
                    return _chkexcludedmInfo.CreateAdapter<Ranorex.CheckBox>(true);
                }
            }

            /// <summary>
            /// The ChkExcludeDM item info.
            /// </summary>
            [RepositoryItemInfo("0fdbe99b-02e6-443e-a166-6a8b08015f3d")]
            public virtual RepoItemInfo ChkExcludeDMInfo
            {
                get
                {
                    return _chkexcludedmInfo;
                }
            }

            /// <summary>
            /// The OkButton item.
            /// </summary>
            [RepositoryItem("80d20184-bca7-45f9-abfd-174fe18edd31")]
            public virtual Ranorex.Button OkButton
            {
                get
                {
                    return _okbuttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The OkButton item info.
            /// </summary>
            [RepositoryItemInfo("80d20184-bca7-45f9-abfd-174fe18edd31")]
            public virtual RepoItemInfo OkButtonInfo
            {
                get
                {
                    return _okbuttonInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}