///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace SQLDMTestAutomation.SSMSRecordingds
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The ClickSQLdmRepositoryInLeftPanel recording.
    /// </summary>
    [TestModule("ef842bbe-065e-438e-87f1-342978211007", ModuleType.Recording, 1)]
    public partial class ClickSQLdmRepositoryInLeftPanel : ITestModule
    {
        /// <summary>
        /// Holds an instance of the SQLDMTestAutomation.SQLDMTestAutomationRepository repository.
        /// </summary>
        public static SQLDMTestAutomation.SQLDMTestAutomationRepository repo = SQLDMTestAutomation.SQLDMTestAutomationRepository.Instance;

        static ClickSQLdmRepositoryInLeftPanel instance = new ClickSQLdmRepositoryInLeftPanel();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public ClickSQLdmRepositoryInLeftPanel()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static ClickSQLdmRepositoryInLeftPanel Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.2")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.2")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Move item 'SSMS.MicrosoftSQLServerManagementStudio.Databases' at Center.", repo.SSMS.MicrosoftSQLServerManagementStudio.DatabasesInfo, new RecordItemIndex(0));
            repo.SSMS.MicrosoftSQLServerManagementStudio.Databases.MoveTo();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left DoubleClick item 'SSMS.MicrosoftSQLServerManagementStudio.Databases' at Center.", repo.SSMS.MicrosoftSQLServerManagementStudio.DatabasesInfo, new RecordItemIndex(1));
            repo.SSMS.MicrosoftSQLServerManagementStudio.Databases.DoubleClick();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Move item 'SSMS.MicrosoftSQLServerManagementStudio.SQLdmRepository' at Center.", repo.SSMS.MicrosoftSQLServerManagementStudio.SQLdmRepositoryInfo, new RecordItemIndex(2));
            repo.SSMS.MicrosoftSQLServerManagementStudio.SQLdmRepository.MoveTo();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Right Click item 'SSMS.MicrosoftSQLServerManagementStudio.SQLdmRepository' at Center.", repo.SSMS.MicrosoftSQLServerManagementStudio.SQLdmRepositoryInfo, new RecordItemIndex(3));
            repo.SSMS.MicrosoftSQLServerManagementStudio.SQLdmRepository.Click(System.Windows.Forms.MouseButtons.Right);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(4));
            Delay.Duration(2000, false);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
