///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace SQLDMTestAutomation.SSMSRecordingds
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The VerifyMonitoredSQLServersTableColumns recording.
    /// </summary>
    [TestModule("c2bda287-5996-49c3-a318-68b71ee525dd", ModuleType.Recording, 1)]
    public partial class VerifyMonitoredSQLServersTableColumns : ITestModule
    {
        /// <summary>
        /// Holds an instance of the SQLDMTestAutomation.SQLDMTestAutomationRepository repository.
        /// </summary>
        public static SQLDMTestAutomation.SQLDMTestAutomationRepository repo = SQLDMTestAutomation.SQLDMTestAutomationRepository.Instance;

        static VerifyMonitoredSQLServersTableColumns instance = new VerifyMonitoredSQLServersTableColumns();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public VerifyMonitoredSQLServersTableColumns()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static VerifyMonitoredSQLServersTableColumns Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.2")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.2")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'SSMS.MicrosoftSQLServerManagementStudio.TableCol_QueryMonitorTopPlanCountFilter'.", repo.SSMS.MicrosoftSQLServerManagementStudio.TableCol_QueryMonitorTopPlanCountFilterInfo, new RecordItemIndex(0));
            Validate.Exists(repo.SSMS.MicrosoftSQLServerManagementStudio.TableCol_QueryMonitorTopPlanCountFilterInfo);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'SSMS.MicrosoftSQLServerManagementStudio.TableCol_QueryMonitorTopPlanCategoryFilter'.", repo.SSMS.MicrosoftSQLServerManagementStudio.TableCol_QueryMonitorTopPlanCategoryFilterInfo, new RecordItemIndex(1));
            Validate.Exists(repo.SSMS.MicrosoftSQLServerManagementStudio.TableCol_QueryMonitorTopPlanCategoryFilterInfo);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'SSMS.MicrosoftSQLServerManagementStudio.TableCol_QueryMonitorQueryStoreMonitoringEnabled'.", repo.SSMS.MicrosoftSQLServerManagementStudio.TableCol_QueryMonitorQueryStoreMonitoringEnabledInfo, new RecordItemIndex(2));
            Validate.Exists(repo.SSMS.MicrosoftSQLServerManagementStudio.TableCol_QueryMonitorQueryStoreMonitoringEnabledInfo);
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
