///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace ADSAutomationPhaseII.TC_10548
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the TC10548Repo element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.2")]
    [RepositoryFolder("873720e9-6af3-4bfd-a945-c111a32b3929")]
    public partial class TC10548Repo : RepoGenBaseFolder
    {
        static TC10548Repo instance = new TC10548Repo();
        TC10548RepoFolders.ApplicationAppFolder _application;
        TC10548RepoFolders.ModesMenuAppFolder _modesmenu;
        TC10548RepoFolders.FloatingMenuAppFolder _floatingmenu;
        TC10548RepoFolders.ServerAppFolder _server;
        TC10548RepoFolders.DataStudioAppFolder _datastudio;
        TC10548RepoFolders.NewProjectAppFolder _newproject;
        TC10548RepoFolders.SelectFolderAppFolder _selectfolder;
        TC10548RepoFolders.SunAwtWindowAppFolder _sunawtwindow;
        TC10548RepoFolders.NewFolderMenuAppFolder _newfoldermenu;
        TC10548RepoFolders.SelectDirectoryAppFolder _selectdirectory;
        TC10548RepoFolders.DatabaseAppFolder _database;
        TC10548RepoFolders.UnmountWindowAppFolder _unmountwindow;
        TC10548RepoFolders.DeleteConfirmAppFolder _deleteconfirm;
        TC10548RepoFolders.RemoveWindowAppFolder _removewindow;
        TC10548RepoFolders.DataTreeAppFolder _datatree;
        TC10548RepoFolders.DB2WindowsAppFolder _db2windows;

        /// <summary>
        /// Gets the singleton class instance representing the TC10548Repo element repository.
        /// </summary>
        [RepositoryFolder("873720e9-6af3-4bfd-a945-c111a32b3929")]
        public static TC10548Repo Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public TC10548Repo() 
            : base("TC10548Repo", "/", null, 0, false, "873720e9-6af3-4bfd-a945-c111a32b3929", ".\\RepositoryImages\\TC10548Repo873720e9.rximgres")
        {
            _application = new TC10548RepoFolders.ApplicationAppFolder(this);
            _modesmenu = new TC10548RepoFolders.ModesMenuAppFolder(this);
            _floatingmenu = new TC10548RepoFolders.FloatingMenuAppFolder(this);
            _server = new TC10548RepoFolders.ServerAppFolder(this);
            _datastudio = new TC10548RepoFolders.DataStudioAppFolder(this);
            _newproject = new TC10548RepoFolders.NewProjectAppFolder(this);
            _selectfolder = new TC10548RepoFolders.SelectFolderAppFolder(this);
            _sunawtwindow = new TC10548RepoFolders.SunAwtWindowAppFolder(this);
            _newfoldermenu = new TC10548RepoFolders.NewFolderMenuAppFolder(this);
            _selectdirectory = new TC10548RepoFolders.SelectDirectoryAppFolder(this);
            _database = new TC10548RepoFolders.DatabaseAppFolder(this);
            _unmountwindow = new TC10548RepoFolders.UnmountWindowAppFolder(this);
            _deleteconfirm = new TC10548RepoFolders.DeleteConfirmAppFolder(this);
            _removewindow = new TC10548RepoFolders.RemoveWindowAppFolder(this);
            _datatree = new TC10548RepoFolders.DataTreeAppFolder(this);
            _db2windows = new TC10548RepoFolders.DB2WindowsAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("873720e9-6af3-4bfd-a945-c111a32b3929")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The Application folder.
        /// </summary>
        [RepositoryFolder("b062234d-34f9-41a1-a07a-d020ff7fb820")]
        public virtual TC10548RepoFolders.ApplicationAppFolder Application
        {
            get { return _application; }
        }

        /// <summary>
        /// The ModesMenu folder.
        /// </summary>
        [RepositoryFolder("3c3db03a-4b1d-490f-b5bb-a8825a123302")]
        public virtual TC10548RepoFolders.ModesMenuAppFolder ModesMenu
        {
            get { return _modesmenu; }
        }

        /// <summary>
        /// The FloatingMenu folder.
        /// </summary>
        [RepositoryFolder("5fad070b-83a6-4fb1-ac30-384255bf61f2")]
        public virtual TC10548RepoFolders.FloatingMenuAppFolder FloatingMenu
        {
            get { return _floatingmenu; }
        }

        /// <summary>
        /// The Server folder.
        /// </summary>
        [RepositoryFolder("198fc4ea-480b-475d-9390-5b725b54b286")]
        public virtual TC10548RepoFolders.ServerAppFolder Server
        {
            get { return _server; }
        }

        /// <summary>
        /// The DataStudio folder.
        /// </summary>
        [RepositoryFolder("f689f428-1ec9-4ad4-b637-215e0253597c")]
        public virtual TC10548RepoFolders.DataStudioAppFolder DataStudio
        {
            get { return _datastudio; }
        }

        /// <summary>
        /// The NewProject folder.
        /// </summary>
        [RepositoryFolder("d02feddb-2a8b-4a3a-9412-edeedfb71fa5")]
        public virtual TC10548RepoFolders.NewProjectAppFolder NewProject
        {
            get { return _newproject; }
        }

        /// <summary>
        /// The SelectFolder folder.
        /// </summary>
        [RepositoryFolder("2af9e6c0-4bdb-401e-888d-e47d2b34d714")]
        public virtual TC10548RepoFolders.SelectFolderAppFolder SelectFolder
        {
            get { return _selectfolder; }
        }

        /// <summary>
        /// The SunAwtWindow folder.
        /// </summary>
        [RepositoryFolder("f97fffa4-056e-4948-845a-822db07e8f2c")]
        public virtual TC10548RepoFolders.SunAwtWindowAppFolder SunAwtWindow
        {
            get { return _sunawtwindow; }
        }

        /// <summary>
        /// The NewFolderMenu folder.
        /// </summary>
        [RepositoryFolder("6f1bd976-6b22-42da-af66-c0ade1fc2460")]
        public virtual TC10548RepoFolders.NewFolderMenuAppFolder NewFolderMenu
        {
            get { return _newfoldermenu; }
        }

        /// <summary>
        /// The SelectDirectory folder.
        /// </summary>
        [RepositoryFolder("95e09dfb-ca22-4e31-985c-b201f4d7c683")]
        public virtual TC10548RepoFolders.SelectDirectoryAppFolder SelectDirectory
        {
            get { return _selectdirectory; }
        }

        /// <summary>
        /// The Database folder.
        /// </summary>
        [RepositoryFolder("af523b1f-5e4b-40cd-ba8d-eb21fab8a136")]
        public virtual TC10548RepoFolders.DatabaseAppFolder Database
        {
            get { return _database; }
        }

        /// <summary>
        /// The UnmountWindow folder.
        /// </summary>
        [RepositoryFolder("6832c317-8695-44d6-92f6-1a1539f35bea")]
        public virtual TC10548RepoFolders.UnmountWindowAppFolder UnmountWindow
        {
            get { return _unmountwindow; }
        }

        /// <summary>
        /// The DeleteConfirm folder.
        /// </summary>
        [RepositoryFolder("73f582aa-fbfe-4e2c-8d61-6c3b8371b3ff")]
        public virtual TC10548RepoFolders.DeleteConfirmAppFolder DeleteConfirm
        {
            get { return _deleteconfirm; }
        }

        /// <summary>
        /// The RemoveWindow folder.
        /// </summary>
        [RepositoryFolder("b431ad76-6e70-4944-a77f-5314099520fe")]
        public virtual TC10548RepoFolders.RemoveWindowAppFolder RemoveWindow
        {
            get { return _removewindow; }
        }

        /// <summary>
        /// The DataTree folder.
        /// </summary>
        [RepositoryFolder("457b1bc5-42ac-4276-a434-1b44c66a2912")]
        public virtual TC10548RepoFolders.DataTreeAppFolder DataTree
        {
            get { return _datatree; }
        }

        /// <summary>
        /// The DB2Windows folder.
        /// </summary>
        [RepositoryFolder("ffab8a1f-e8e3-4af5-9ee3-8ff3682d839d")]
        public virtual TC10548RepoFolders.DB2WindowsAppFolder DB2Windows
        {
            get { return _db2windows; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.2")]
    public partial class TC10548RepoFolders
    {
        /// <summary>
        /// The ApplicationAppFolder folder.
        /// </summary>
        [RepositoryFolder("b062234d-34f9-41a1-a07a-d020ff7fb820")]
        public partial class ApplicationAppFolder : RepoGenBaseFolder
        {
            TC10548RepoFolders.SettingsFolder _settings;
            RepoItemInfo _f1menuInfo;
            RepoItemInfo _treeitemInfo;
            RepoItemInfo _projectstreeInfo;
            RepoItemInfo _userfilesInfo;
            RepoItemInfo _newprojectfileInfo;
            RepoItemInfo _f3menuInfo;
            RepoItemInfo _filesystemtreeInfo;
            RepoItemInfo _f2menuInfo;
            RepoItemInfo _ddlInfo;
            RepoItemInfo _db2sqlInfo;
            RepoItemInfo _windowstabsInfo;
            RepoItemInfo _adstableInfo;
            RepoItemInfo _desktopInfo;

            /// <summary>
            /// Creates a new Application  folder.
            /// </summary>
            public ApplicationAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Application", "/form[@title='Aqua Data Studio']", parentFolder, 30000, null, true, "b062234d-34f9-41a1-a07a-d020ff7fb820", "")
            {
                _settings = new TC10548RepoFolders.SettingsFolder(this);
                _f1menuInfo = new RepoItemInfo(this, "F1Menu", ".//container[@name='myLeftStripe']/checkbox[@text='F1: Servers']", 30000, null, "489913cd-c4a5-48d0-80c5-29e769b9f399");
                _treeitemInfo = new RepoItemInfo(this, "TreeItem", "container[@type='ToolWindowsPane']/container[@name='myLayeredPane']/container[@name='myVerticalSplitter']/container[@name='myInnerComponent']/container[@name='myFirstComponent']//container[@name='viewport']/tree[@name='schemaTree']/?/?/treeitem[@text='Local Database Servers']", 30000, null, "dd817a3d-ff38-459e-af67-b151e8178be2");
                _projectstreeInfo = new RepoItemInfo(this, "ProjectsTree", ".//container[@type='ToolWindowsPane']/container[@name='myLayeredPane']/container[@name='myVerticalSplitter']/container[@name='myInnerComponent']/container[@name='myFirstComponent']//container[@name='viewport']/tree[@name='projectTree']/treeitem[@text='Projects']", 30000, null, "618ab7c1-8eff-4d80-9c2e-60c027058ff9");
                _userfilesInfo = new RepoItemInfo(this, "UserFiles", ".//container[@type='ToolWindowsPane']/container[@name='myLayeredPane']/container[@name='myVerticalSplitter']/container[@name='myInnerComponent']/container[@name='myFirstComponent']/?/?/container[@type='NonOpaquePanel']//container[@name='viewport']/tree[@name='fGA']//treeitem[@text='User Files']", 30000, null, "c6d999b1-8ab5-4a06-9b50-83045fde4fbf");
                _newprojectfileInfo = new RepoItemInfo(this, "NewProjectFile", ".//container[@type='ToolWindowsPane']/container[@name='myLayeredPane']/container[@name='myVerticalSplitter']/container[@name='myInnerComponent']/container[@name='myFirstComponent']/?/?/container[@type='NonOpaquePanel']//container[@name='viewport']/tree[@name='fGA']//treeitem[@text='AquaScripts']/treeitem[@text~'^Database\\ Schema\\ and\\ Data\\ ']", 30000, null, "2a5d3463-33bf-4d99-9088-ec77212ad642");
                _f3menuInfo = new RepoItemInfo(this, "F3Menu", ".//container[@name='myLeftStripe']/checkbox[@text='F3: Projects']", 30000, null, "bd0501ce-6dee-46c8-9d89-7e7ba12444a4");
                _filesystemtreeInfo = new RepoItemInfo(this, "FileSystemtree", "container[@type='ToolWindowsPane']/container[@name='myLayeredPane']/container[@name='myVerticalSplitter']/container[@name='myInnerComponent']/container[@name='myFirstComponent']//container[@name='viewport']/tree[@name='scriptTree']/treeitem[@text='Filesystem']", 30000, null, "2b5207a4-80c1-478c-9aaa-f876310f38fa");
                _f2menuInfo = new RepoItemInfo(this, "F2Menu", ".//container[@name='myLeftStripe']/checkbox[@text='F2: Files']", 30000, null, "0420b920-720d-4464-b760-f446d5f25916");
                _ddlInfo = new RepoItemInfo(this, "DDL", ".//container[@type='ToolWindowsPane']/container[@name='myLayeredPane']/container[@name='myVerticalSplitter']/container[@name='myInnerComponent']/container[@name='myFirstComponent']//container[@name='viewport']/tree[@name='scriptTree']/?/?/treeitem[@text='C:\\DDL']", 30000, null, "9c739c5a-9c06-436c-bf1f-8d7364541bc0");
                _db2sqlInfo = new RepoItemInfo(this, "DB2SQL", ".//container[@type='ToolWindowsPane']/container[@name='myLayeredPane']/container[@name='myVerticalSplitter']/container[@name='myInnerComponent']/container[@name='myFirstComponent']/?/?/container[@type='NonOpaquePanel']//container[@name='viewport']/tree[@name='scriptTree']//treeitem[@text='DB2LUW.sql']", 30000, null, "e1bffd08-1fb2-4488-bb91-e2166f605faa");
                _windowstabsInfo = new RepoItemInfo(this, "WindowsTabs", ".//container[@type='ToolWindowsPane']/container[@name='myLayeredPane']//container[@type='eꀼ⢷ꊩꂚObjectinstanceof']//tabpage[@title~'^root@Amazon\\ Redshift\\ \\[DB2']", 30000, null, "9736c743-0d41-482d-8f44-da61c2ea60e5");
                _adstableInfo = new RepoItemInfo(this, "AdsTable", ".//container[@type='ToolWindowsPane']/container[@name='myLayeredPane']/container[@name='myVerticalSplitter']/container[@name='myInnerComponent']/container[@name='myFirstComponent']//container[@name='viewport']/tree[@name='scriptTree']/?/?/treeitem[@text='ads Table']", 30000, null, "6c4e88e9-2477-4be9-b797-4fc18e8ab525");
                _desktopInfo = new RepoItemInfo(this, "Desktop", ".//container[@type='ToolWindowsPane']/container[@name='myLayeredPane']/container[@name='myVerticalSplitter']/container[@name='myInnerComponent']/container[@name='myFirstComponent']//container[@name='viewport']/tree[@name='scriptTree']/?/?/treeitem[@text='Desktop']", 30000, null, "72437dae-0eac-48cf-be10-d876b3953f75");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("b062234d-34f9-41a1-a07a-d020ff7fb820")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("b062234d-34f9-41a1-a07a-d020ff7fb820")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The F1Menu item.
            /// </summary>
            [RepositoryItem("489913cd-c4a5-48d0-80c5-29e769b9f399")]
            public virtual Ranorex.CheckBox F1Menu
            {
                get
                {
                    return _f1menuInfo.CreateAdapter<Ranorex.CheckBox>(true);
                }
            }

            /// <summary>
            /// The F1Menu item info.
            /// </summary>
            [RepositoryItemInfo("489913cd-c4a5-48d0-80c5-29e769b9f399")]
            public virtual RepoItemInfo F1MenuInfo
            {
                get
                {
                    return _f1menuInfo;
                }
            }

            /// <summary>
            /// The TreeItem item.
            /// </summary>
            [RepositoryItem("dd817a3d-ff38-459e-af67-b151e8178be2")]
            public virtual Ranorex.TreeItem TreeItem
            {
                get
                {
                    return _treeitemInfo.CreateAdapter<Ranorex.TreeItem>(true);
                }
            }

            /// <summary>
            /// The TreeItem item info.
            /// </summary>
            [RepositoryItemInfo("dd817a3d-ff38-459e-af67-b151e8178be2")]
            public virtual RepoItemInfo TreeItemInfo
            {
                get
                {
                    return _treeitemInfo;
                }
            }

            /// <summary>
            /// The ProjectsTree item.
            /// </summary>
            [RepositoryItem("618ab7c1-8eff-4d80-9c2e-60c027058ff9")]
            public virtual Ranorex.TreeItem ProjectsTree
            {
                get
                {
                    return _projectstreeInfo.CreateAdapter<Ranorex.TreeItem>(true);
                }
            }

            /// <summary>
            /// The ProjectsTree item info.
            /// </summary>
            [RepositoryItemInfo("618ab7c1-8eff-4d80-9c2e-60c027058ff9")]
            public virtual RepoItemInfo ProjectsTreeInfo
            {
                get
                {
                    return _projectstreeInfo;
                }
            }

            /// <summary>
            /// The UserFiles item.
            /// </summary>
            [RepositoryItem("c6d999b1-8ab5-4a06-9b50-83045fde4fbf")]
            public virtual Ranorex.TreeItem UserFiles
            {
                get
                {
                    return _userfilesInfo.CreateAdapter<Ranorex.TreeItem>(true);
                }
            }

            /// <summary>
            /// The UserFiles item info.
            /// </summary>
            [RepositoryItemInfo("c6d999b1-8ab5-4a06-9b50-83045fde4fbf")]
            public virtual RepoItemInfo UserFilesInfo
            {
                get
                {
                    return _userfilesInfo;
                }
            }

            /// <summary>
            /// The NewProjectFile item.
            /// </summary>
            [RepositoryItem("2a5d3463-33bf-4d99-9088-ec77212ad642")]
            public virtual Ranorex.TreeItem NewProjectFile
            {
                get
                {
                    return _newprojectfileInfo.CreateAdapter<Ranorex.TreeItem>(true);
                }
            }

            /// <summary>
            /// The NewProjectFile item info.
            /// </summary>
            [RepositoryItemInfo("2a5d3463-33bf-4d99-9088-ec77212ad642")]
            public virtual RepoItemInfo NewProjectFileInfo
            {
                get
                {
                    return _newprojectfileInfo;
                }
            }

            /// <summary>
            /// The F3Menu item.
            /// </summary>
            [RepositoryItem("bd0501ce-6dee-46c8-9d89-7e7ba12444a4")]
            public virtual Ranorex.CheckBox F3Menu
            {
                get
                {
                    return _f3menuInfo.CreateAdapter<Ranorex.CheckBox>(true);
                }
            }

            /// <summary>
            /// The F3Menu item info.
            /// </summary>
            [RepositoryItemInfo("bd0501ce-6dee-46c8-9d89-7e7ba12444a4")]
            public virtual RepoItemInfo F3MenuInfo
            {
                get
                {
                    return _f3menuInfo;
                }
            }

            /// <summary>
            /// The FileSystemtree item.
            /// </summary>
            [RepositoryItem("2b5207a4-80c1-478c-9aaa-f876310f38fa")]
            public virtual Ranorex.TreeItem FileSystemtree
            {
                get
                {
                    return _filesystemtreeInfo.CreateAdapter<Ranorex.TreeItem>(true);
                }
            }

            /// <summary>
            /// The FileSystemtree item info.
            /// </summary>
            [RepositoryItemInfo("2b5207a4-80c1-478c-9aaa-f876310f38fa")]
            public virtual RepoItemInfo FileSystemtreeInfo
            {
                get
                {
                    return _filesystemtreeInfo;
                }
            }

            /// <summary>
            /// The F2Menu item.
            /// </summary>
            [RepositoryItem("0420b920-720d-4464-b760-f446d5f25916")]
            public virtual Ranorex.CheckBox F2Menu
            {
                get
                {
                    return _f2menuInfo.CreateAdapter<Ranorex.CheckBox>(true);
                }
            }

            /// <summary>
            /// The F2Menu item info.
            /// </summary>
            [RepositoryItemInfo("0420b920-720d-4464-b760-f446d5f25916")]
            public virtual RepoItemInfo F2MenuInfo
            {
                get
                {
                    return _f2menuInfo;
                }
            }

            /// <summary>
            /// The DDL item.
            /// </summary>
            [RepositoryItem("9c739c5a-9c06-436c-bf1f-8d7364541bc0")]
            public virtual Ranorex.TreeItem DDL
            {
                get
                {
                    return _ddlInfo.CreateAdapter<Ranorex.TreeItem>(true);
                }
            }

            /// <summary>
            /// The DDL item info.
            /// </summary>
            [RepositoryItemInfo("9c739c5a-9c06-436c-bf1f-8d7364541bc0")]
            public virtual RepoItemInfo DDLInfo
            {
                get
                {
                    return _ddlInfo;
                }
            }

            /// <summary>
            /// The DB2SQL item.
            /// </summary>
            [RepositoryItem("e1bffd08-1fb2-4488-bb91-e2166f605faa")]
            public virtual Ranorex.TreeItem DB2SQL
            {
                get
                {
                    return _db2sqlInfo.CreateAdapter<Ranorex.TreeItem>(true);
                }
            }

            /// <summary>
            /// The DB2SQL item info.
            /// </summary>
            [RepositoryItemInfo("e1bffd08-1fb2-4488-bb91-e2166f605faa")]
            public virtual RepoItemInfo DB2SQLInfo
            {
                get
                {
                    return _db2sqlInfo;
                }
            }

            /// <summary>
            /// The WindowsTabs item.
            /// </summary>
            [RepositoryItem("9736c743-0d41-482d-8f44-da61c2ea60e5")]
            public virtual Ranorex.TabPage WindowsTabs
            {
                get
                {
                    return _windowstabsInfo.CreateAdapter<Ranorex.TabPage>(true);
                }
            }

            /// <summary>
            /// The WindowsTabs item info.
            /// </summary>
            [RepositoryItemInfo("9736c743-0d41-482d-8f44-da61c2ea60e5")]
            public virtual RepoItemInfo WindowsTabsInfo
            {
                get
                {
                    return _windowstabsInfo;
                }
            }

            /// <summary>
            /// The AdsTable item.
            /// </summary>
            [RepositoryItem("6c4e88e9-2477-4be9-b797-4fc18e8ab525")]
            public virtual Ranorex.TreeItem AdsTable
            {
                get
                {
                    return _adstableInfo.CreateAdapter<Ranorex.TreeItem>(true);
                }
            }

            /// <summary>
            /// The AdsTable item info.
            /// </summary>
            [RepositoryItemInfo("6c4e88e9-2477-4be9-b797-4fc18e8ab525")]
            public virtual RepoItemInfo AdsTableInfo
            {
                get
                {
                    return _adstableInfo;
                }
            }

            /// <summary>
            /// The Desktop item.
            /// </summary>
            [RepositoryItem("72437dae-0eac-48cf-be10-d876b3953f75")]
            public virtual Ranorex.TreeItem Desktop
            {
                get
                {
                    return _desktopInfo.CreateAdapter<Ranorex.TreeItem>(true);
                }
            }

            /// <summary>
            /// The Desktop item info.
            /// </summary>
            [RepositoryItemInfo("72437dae-0eac-48cf-be10-d876b3953f75")]
            public virtual RepoItemInfo DesktopInfo
            {
                get
                {
                    return _desktopInfo;
                }
            }

            /// <summary>
            /// The Settings folder.
            /// </summary>
            [RepositoryFolder("4a94d1fe-6c41-4f14-a9d4-fe6baf8bd9ab")]
            public virtual TC10548RepoFolders.SettingsFolder Settings
            {
                get { return _settings; }
            }
        }

        /// <summary>
        /// The SettingsFolder folder.
        /// </summary>
        [RepositoryFolder("4a94d1fe-6c41-4f14-a9d4-fe6baf8bd9ab")]
        public partial class SettingsFolder : RepoGenBaseFolder
        {
            RepoItemInfo _settingiconInfo;
            RepoItemInfo _settingicondInfo;

            /// <summary>
            /// Creates a new Settings  folder.
            /// </summary>
            public SettingsFolder(RepoGenBaseFolder parentFolder) :
                    base("Settings", "", parentFolder, 0, null, false, "4a94d1fe-6c41-4f14-a9d4-fe6baf8bd9ab", "")
            {
                _settingiconInfo = new RepoItemInfo(this, "SettingIcon", ".//container[@type='ToolWindowsPane']/container[@name='myLayeredPane']/?/?/container[@type='ThreeComponentsSplitter']/container[@name='myFirstComponent']//container[@type='ToolWindowHeader$3']", 30000, null, "dd3e688b-b8db-4004-bb86-f748632cd4e6");
                _settingicondInfo = new RepoItemInfo(this, "SettingIconD", ".//container[@type='ToolWindowsPane']/container[@name='myLayeredPane']//container[@name='myHeader']/?/?/container[@type='ToolWindowHeader$3']", 30000, null, "d1c1bdae-3bd4-479c-a632-ade33cfaf25f");
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("4a94d1fe-6c41-4f14-a9d4-fe6baf8bd9ab")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The SettingIcon item.
            /// </summary>
            [RepositoryItem("dd3e688b-b8db-4004-bb86-f748632cd4e6")]
            public virtual Ranorex.Container SettingIcon
            {
                get
                {
                    return _settingiconInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The SettingIcon item info.
            /// </summary>
            [RepositoryItemInfo("dd3e688b-b8db-4004-bb86-f748632cd4e6")]
            public virtual RepoItemInfo SettingIconInfo
            {
                get
                {
                    return _settingiconInfo;
                }
            }

            /// <summary>
            /// The SettingIconD item.
            /// </summary>
            [RepositoryItem("d1c1bdae-3bd4-479c-a632-ade33cfaf25f")]
            public virtual Ranorex.Container SettingIconD
            {
                get
                {
                    return _settingicondInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The SettingIconD item info.
            /// </summary>
            [RepositoryItemInfo("d1c1bdae-3bd4-479c-a632-ade33cfaf25f")]
            public virtual RepoItemInfo SettingIconDInfo
            {
                get
                {
                    return _settingicondInfo;
                }
            }
        }

        /// <summary>
        /// The ModesMenuAppFolder folder.
        /// </summary>
        [RepositoryFolder("3c3db03a-4b1d-490f-b5bb-a8825a123302")]
        public partial class ModesMenuAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _floatingmodeInfo;
            RepoItemInfo _contextmenuInfo;
            RepoItemInfo _pinnedmodeInfo;
            RepoItemInfo _docked_modeInfo;
            RepoItemInfo _splitmodeInfo;
            RepoItemInfo _momentumInfo;

            /// <summary>
            /// Creates a new ModesMenu  folder.
            /// </summary>
            public ModesMenuAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ModesMenu", "/form[@processname='datastudio']", parentFolder, 30000, null, true, "3c3db03a-4b1d-490f-b5bb-a8825a123302", "")
            {
                _floatingmodeInfo = new RepoItemInfo(this, "FloatingMode", ".//menuitem[@text='Floating Mode']", 30000, null, "d20503b6-5dc0-45ef-a4fb-5864a5679ef9");
                _contextmenuInfo = new RepoItemInfo(this, "ContextMenu", ".//contextmenu", 30000, null, "9d29fe36-afbd-4bb7-be98-50699a675415");
                _pinnedmodeInfo = new RepoItemInfo(this, "PinnedMode", ".//menuitem[@text='Pinned Mode']", 30000, null, "bf33a432-5672-40ff-a024-f232f962765d");
                _docked_modeInfo = new RepoItemInfo(this, "Docked_Mode", ".//menuitem[@text='Docked Mode']", 30000, null, "1a9f6345-e68d-4246-9cfa-21e9860f8af1");
                _splitmodeInfo = new RepoItemInfo(this, "SplitMode", ".//menuitem[@text='Split Mode']", 30000, null, "b9a04402-66f5-4222-a791-aa8160bf6ee3");
                _momentumInfo = new RepoItemInfo(this, "Momentum", ".//menuitem", 30000, null, "ed7279c5-796e-4272-86f9-73df8e62eac4");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("3c3db03a-4b1d-490f-b5bb-a8825a123302")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("3c3db03a-4b1d-490f-b5bb-a8825a123302")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The FloatingMode item.
            /// </summary>
            [RepositoryItem("d20503b6-5dc0-45ef-a4fb-5864a5679ef9")]
            public virtual Ranorex.MenuItem FloatingMode
            {
                get
                {
                    return _floatingmodeInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The FloatingMode item info.
            /// </summary>
            [RepositoryItemInfo("d20503b6-5dc0-45ef-a4fb-5864a5679ef9")]
            public virtual RepoItemInfo FloatingModeInfo
            {
                get
                {
                    return _floatingmodeInfo;
                }
            }

            /// <summary>
            /// The ContextMenu item.
            /// </summary>
            [RepositoryItem("9d29fe36-afbd-4bb7-be98-50699a675415")]
            public virtual Ranorex.ContextMenu ContextMenu
            {
                get
                {
                    return _contextmenuInfo.CreateAdapter<Ranorex.ContextMenu>(true);
                }
            }

            /// <summary>
            /// The ContextMenu item info.
            /// </summary>
            [RepositoryItemInfo("9d29fe36-afbd-4bb7-be98-50699a675415")]
            public virtual RepoItemInfo ContextMenuInfo
            {
                get
                {
                    return _contextmenuInfo;
                }
            }

            /// <summary>
            /// The PinnedMode item.
            /// </summary>
            [RepositoryItem("bf33a432-5672-40ff-a024-f232f962765d")]
            public virtual Ranorex.MenuItem PinnedMode
            {
                get
                {
                    return _pinnedmodeInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The PinnedMode item info.
            /// </summary>
            [RepositoryItemInfo("bf33a432-5672-40ff-a024-f232f962765d")]
            public virtual RepoItemInfo PinnedModeInfo
            {
                get
                {
                    return _pinnedmodeInfo;
                }
            }

            /// <summary>
            /// The Docked_Mode item.
            /// </summary>
            [RepositoryItem("1a9f6345-e68d-4246-9cfa-21e9860f8af1")]
            public virtual Ranorex.MenuItem Docked_Mode
            {
                get
                {
                    return _docked_modeInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The Docked_Mode item info.
            /// </summary>
            [RepositoryItemInfo("1a9f6345-e68d-4246-9cfa-21e9860f8af1")]
            public virtual RepoItemInfo Docked_ModeInfo
            {
                get
                {
                    return _docked_modeInfo;
                }
            }

            /// <summary>
            /// The SplitMode item.
            /// </summary>
            [RepositoryItem("b9a04402-66f5-4222-a791-aa8160bf6ee3")]
            public virtual Ranorex.MenuItem SplitMode
            {
                get
                {
                    return _splitmodeInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The SplitMode item info.
            /// </summary>
            [RepositoryItemInfo("b9a04402-66f5-4222-a791-aa8160bf6ee3")]
            public virtual RepoItemInfo SplitModeInfo
            {
                get
                {
                    return _splitmodeInfo;
                }
            }

            /// <summary>
            /// The Momentum item.
            /// </summary>
            [RepositoryItem("ed7279c5-796e-4272-86f9-73df8e62eac4")]
            public virtual Ranorex.MenuItem Momentum
            {
                get
                {
                    return _momentumInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The Momentum item info.
            /// </summary>
            [RepositoryItemInfo("ed7279c5-796e-4272-86f9-73df8e62eac4")]
            public virtual RepoItemInfo MomentumInfo
            {
                get
                {
                    return _momentumInfo;
                }
            }
        }

        /// <summary>
        /// The FloatingMenuAppFolder folder.
        /// </summary>
        [RepositoryFolder("5fad070b-83a6-4fb1-ac30-384255bf61f2")]
        public partial class FloatingMenuAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _floatingmodeInfo;
            RepoItemInfo _contextmenu1Info;

            /// <summary>
            /// Creates a new FloatingMenu  folder.
            /// </summary>
            public FloatingMenuAppFolder(RepoGenBaseFolder parentFolder) :
                    base("FloatingMenu", "/form[@class='SunAwtWindow']", parentFolder, 30000, null, true, "5fad070b-83a6-4fb1-ac30-384255bf61f2", "")
            {
                _floatingmodeInfo = new RepoItemInfo(this, "FloatingMode", ".//menuitem[@text='Floating Mode']", 30000, null, "144bd8a8-62ad-4f7f-93b9-138bbbeb548b");
                _contextmenu1Info = new RepoItemInfo(this, "ContextMenu1", ".//contextmenu", 30000, null, "2380fb98-0e2e-4449-bd54-06346f286202");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("5fad070b-83a6-4fb1-ac30-384255bf61f2")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("5fad070b-83a6-4fb1-ac30-384255bf61f2")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The FloatingMode item.
            /// </summary>
            [RepositoryItem("144bd8a8-62ad-4f7f-93b9-138bbbeb548b")]
            public virtual Ranorex.MenuItem FloatingMode
            {
                get
                {
                    return _floatingmodeInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The FloatingMode item info.
            /// </summary>
            [RepositoryItemInfo("144bd8a8-62ad-4f7f-93b9-138bbbeb548b")]
            public virtual RepoItemInfo FloatingModeInfo
            {
                get
                {
                    return _floatingmodeInfo;
                }
            }

            /// <summary>
            /// The ContextMenu1 item.
            /// </summary>
            [RepositoryItem("2380fb98-0e2e-4449-bd54-06346f286202")]
            public virtual Ranorex.ContextMenu ContextMenu1
            {
                get
                {
                    return _contextmenu1Info.CreateAdapter<Ranorex.ContextMenu>(true);
                }
            }

            /// <summary>
            /// The ContextMenu1 item info.
            /// </summary>
            [RepositoryItemInfo("2380fb98-0e2e-4449-bd54-06346f286202")]
            public virtual RepoItemInfo ContextMenu1Info
            {
                get
                {
                    return _contextmenu1Info;
                }
            }
        }

        /// <summary>
        /// The ServerAppFolder folder.
        /// </summary>
        [RepositoryFolder("198fc4ea-480b-475d-9390-5b725b54b286")]
        public partial class ServerAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _settingicon1Info;
            RepoItemInfo _jpanelmenuInfo;

            /// <summary>
            /// Creates a new Server  folder.
            /// </summary>
            public ServerAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Server", "/form[@title='Servers']", parentFolder, 30000, null, true, "198fc4ea-480b-475d-9390-5b725b54b286", "")
            {
                _settingicon1Info = new RepoItemInfo(this, "SettingIcon1", ".//container[@name='myInternalDecorator']/?/?/container[@name='myHeader']/?/?/container[@type='ToolWindowHeader$3']", 30000, null, "eae64fd0-b7ff-482b-9783-4fcbc758858a");
                _jpanelmenuInfo = new RepoItemInfo(this, "JpanelMenu", ".//container[@name='myInternalDecorator']/?/?/container[@name='myHeader']/container[@type='JPanel']", 30000, null, "5bbb48a3-e039-4574-a25e-ac550f0f0a19");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("198fc4ea-480b-475d-9390-5b725b54b286")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("198fc4ea-480b-475d-9390-5b725b54b286")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The SettingIcon1 item.
            /// </summary>
            [RepositoryItem("eae64fd0-b7ff-482b-9783-4fcbc758858a")]
            public virtual Ranorex.Container SettingIcon1
            {
                get
                {
                    return _settingicon1Info.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The SettingIcon1 item info.
            /// </summary>
            [RepositoryItemInfo("eae64fd0-b7ff-482b-9783-4fcbc758858a")]
            public virtual RepoItemInfo SettingIcon1Info
            {
                get
                {
                    return _settingicon1Info;
                }
            }

            /// <summary>
            /// The JpanelMenu item.
            /// </summary>
            [RepositoryItem("5bbb48a3-e039-4574-a25e-ac550f0f0a19")]
            public virtual Ranorex.Container JpanelMenu
            {
                get
                {
                    return _jpanelmenuInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The JpanelMenu item info.
            /// </summary>
            [RepositoryItemInfo("5bbb48a3-e039-4574-a25e-ac550f0f0a19")]
            public virtual RepoItemInfo JpanelMenuInfo
            {
                get
                {
                    return _jpanelmenuInfo;
                }
            }
        }

        /// <summary>
        /// The DataStudioAppFolder folder.
        /// </summary>
        [RepositoryFolder("f689f428-1ec9-4ad4-b637-215e0253597c")]
        public partial class DataStudioAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _newprojectmenuInfo;
            RepoItemInfo _removemenuInfo;
            RepoItemInfo _closeallInfo;
            RepoItemInfo _newfoldermenuInfo;
            RepoItemInfo _showdesktopInfo;
            RepoItemInfo _showmountdirectoryInfo;
            RepoItemInfo _newfolderInfo;
            RepoItemInfo _unmountdirectoryInfo;
            RepoItemInfo _deleteadstableInfo;
            RepoItemInfo _hidedesktopInfo;
            RepoItemInfo _tabcloseInfo;

            /// <summary>
            /// Creates a new DataStudio  folder.
            /// </summary>
            public DataStudioAppFolder(RepoGenBaseFolder parentFolder) :
                    base("DataStudio", "/form[@processname='datastudio']", parentFolder, 30000, null, true, "f689f428-1ec9-4ad4-b637-215e0253597c", "")
            {
                _newprojectmenuInfo = new RepoItemInfo(this, "NewProjectMenu", ".//menuitem[@text='New Project']", 30000, null, "602ad7ce-7b4b-4250-b9a7-07d31ae90667");
                _removemenuInfo = new RepoItemInfo(this, "RemoveMenu", ".//menuitem[@text='Remove']", 30000, null, "b57b66db-5df6-4ae9-83c1-121232adcf3b");
                _closeallInfo = new RepoItemInfo(this, "CloseAll", ".//menuitem[@name='TabDocumentPane.closeAll']", 30000, null, "ec093472-e162-4a8b-ab5b-ac8fb0455d6d");
                _newfoldermenuInfo = new RepoItemInfo(this, "NewFolderMenu", ".//menuitem[@text='New Folder']", 30000, null, "516685de-ec58-4f63-90d8-4ffc1e786d0a");
                _showdesktopInfo = new RepoItemInfo(this, "ShowDesktop", ".//menuitem[@text='Show Desktop']", 30000, null, "5e3d0233-a822-4825-811d-d497b0651ee5");
                _showmountdirectoryInfo = new RepoItemInfo(this, "ShowMountDirectory", ".//menuitem[@text='Mount Directory']", 30000, null, "a1d27dff-e03c-49ec-87a6-1273bfa512b8");
                _newfolderInfo = new RepoItemInfo(this, "NewFolder", ".//menuitem[@text='New Folder']", 30000, null, "68821575-de9b-40a0-89d3-c3e869f3f083");
                _unmountdirectoryInfo = new RepoItemInfo(this, "UnMountDirectory", ".//menuitem[@text='Unmount Directory']", 30000, null, "1bdce418-1bd9-4965-bcb4-e29269eda2ed");
                _deleteadstableInfo = new RepoItemInfo(this, "DeleteAdsTable", ".//menuitem[@text='Delete']", 30000, null, "d0582e05-ebf1-483c-b34d-09bfaee26b4d");
                _hidedesktopInfo = new RepoItemInfo(this, "HideDesktop", ".//menuitem[@text='Hide Desktop']", 30000, null, "a78833f6-d78f-43da-999b-943cf2fc03d2");
                _tabcloseInfo = new RepoItemInfo(this, "TabClose", ".//menuitem[@name='TabDocumentPane.close']", 30000, null, "1b89fafc-fe0e-4d94-b980-24324cab980c");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("f689f428-1ec9-4ad4-b637-215e0253597c")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("f689f428-1ec9-4ad4-b637-215e0253597c")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The NewProjectMenu item.
            /// </summary>
            [RepositoryItem("602ad7ce-7b4b-4250-b9a7-07d31ae90667")]
            public virtual Ranorex.MenuItem NewProjectMenu
            {
                get
                {
                    return _newprojectmenuInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The NewProjectMenu item info.
            /// </summary>
            [RepositoryItemInfo("602ad7ce-7b4b-4250-b9a7-07d31ae90667")]
            public virtual RepoItemInfo NewProjectMenuInfo
            {
                get
                {
                    return _newprojectmenuInfo;
                }
            }

            /// <summary>
            /// The RemoveMenu item.
            /// </summary>
            [RepositoryItem("b57b66db-5df6-4ae9-83c1-121232adcf3b")]
            public virtual Ranorex.MenuItem RemoveMenu
            {
                get
                {
                    return _removemenuInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The RemoveMenu item info.
            /// </summary>
            [RepositoryItemInfo("b57b66db-5df6-4ae9-83c1-121232adcf3b")]
            public virtual RepoItemInfo RemoveMenuInfo
            {
                get
                {
                    return _removemenuInfo;
                }
            }

            /// <summary>
            /// The CloseAll item.
            /// </summary>
            [RepositoryItem("ec093472-e162-4a8b-ab5b-ac8fb0455d6d")]
            public virtual Ranorex.MenuItem CloseAll
            {
                get
                {
                    return _closeallInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The CloseAll item info.
            /// </summary>
            [RepositoryItemInfo("ec093472-e162-4a8b-ab5b-ac8fb0455d6d")]
            public virtual RepoItemInfo CloseAllInfo
            {
                get
                {
                    return _closeallInfo;
                }
            }

            /// <summary>
            /// The NewFolderMenu item.
            /// </summary>
            [RepositoryItem("516685de-ec58-4f63-90d8-4ffc1e786d0a")]
            public virtual Ranorex.MenuItem NewFolderMenu
            {
                get
                {
                    return _newfoldermenuInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The NewFolderMenu item info.
            /// </summary>
            [RepositoryItemInfo("516685de-ec58-4f63-90d8-4ffc1e786d0a")]
            public virtual RepoItemInfo NewFolderMenuInfo
            {
                get
                {
                    return _newfoldermenuInfo;
                }
            }

            /// <summary>
            /// The ShowDesktop item.
            /// </summary>
            [RepositoryItem("5e3d0233-a822-4825-811d-d497b0651ee5")]
            public virtual Ranorex.MenuItem ShowDesktop
            {
                get
                {
                    return _showdesktopInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The ShowDesktop item info.
            /// </summary>
            [RepositoryItemInfo("5e3d0233-a822-4825-811d-d497b0651ee5")]
            public virtual RepoItemInfo ShowDesktopInfo
            {
                get
                {
                    return _showdesktopInfo;
                }
            }

            /// <summary>
            /// The ShowMountDirectory item.
            /// </summary>
            [RepositoryItem("a1d27dff-e03c-49ec-87a6-1273bfa512b8")]
            public virtual Ranorex.MenuItem ShowMountDirectory
            {
                get
                {
                    return _showmountdirectoryInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The ShowMountDirectory item info.
            /// </summary>
            [RepositoryItemInfo("a1d27dff-e03c-49ec-87a6-1273bfa512b8")]
            public virtual RepoItemInfo ShowMountDirectoryInfo
            {
                get
                {
                    return _showmountdirectoryInfo;
                }
            }

            /// <summary>
            /// The NewFolder item.
            /// </summary>
            [RepositoryItem("68821575-de9b-40a0-89d3-c3e869f3f083")]
            public virtual Ranorex.MenuItem NewFolder
            {
                get
                {
                    return _newfolderInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The NewFolder item info.
            /// </summary>
            [RepositoryItemInfo("68821575-de9b-40a0-89d3-c3e869f3f083")]
            public virtual RepoItemInfo NewFolderInfo
            {
                get
                {
                    return _newfolderInfo;
                }
            }

            /// <summary>
            /// The UnMountDirectory item.
            /// </summary>
            [RepositoryItem("1bdce418-1bd9-4965-bcb4-e29269eda2ed")]
            public virtual Ranorex.MenuItem UnMountDirectory
            {
                get
                {
                    return _unmountdirectoryInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The UnMountDirectory item info.
            /// </summary>
            [RepositoryItemInfo("1bdce418-1bd9-4965-bcb4-e29269eda2ed")]
            public virtual RepoItemInfo UnMountDirectoryInfo
            {
                get
                {
                    return _unmountdirectoryInfo;
                }
            }

            /// <summary>
            /// The DeleteAdsTable item.
            /// </summary>
            [RepositoryItem("d0582e05-ebf1-483c-b34d-09bfaee26b4d")]
            public virtual Ranorex.MenuItem DeleteAdsTable
            {
                get
                {
                    return _deleteadstableInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The DeleteAdsTable item info.
            /// </summary>
            [RepositoryItemInfo("d0582e05-ebf1-483c-b34d-09bfaee26b4d")]
            public virtual RepoItemInfo DeleteAdsTableInfo
            {
                get
                {
                    return _deleteadstableInfo;
                }
            }

            /// <summary>
            /// The HideDesktop item.
            /// </summary>
            [RepositoryItem("a78833f6-d78f-43da-999b-943cf2fc03d2")]
            public virtual Ranorex.MenuItem HideDesktop
            {
                get
                {
                    return _hidedesktopInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The HideDesktop item info.
            /// </summary>
            [RepositoryItemInfo("a78833f6-d78f-43da-999b-943cf2fc03d2")]
            public virtual RepoItemInfo HideDesktopInfo
            {
                get
                {
                    return _hidedesktopInfo;
                }
            }

            /// <summary>
            /// The TabClose item.
            /// </summary>
            [RepositoryItem("1b89fafc-fe0e-4d94-b980-24324cab980c")]
            public virtual Ranorex.MenuItem TabClose
            {
                get
                {
                    return _tabcloseInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The TabClose item info.
            /// </summary>
            [RepositoryItemInfo("1b89fafc-fe0e-4d94-b980-24324cab980c")]
            public virtual RepoItemInfo TabCloseInfo
            {
                get
                {
                    return _tabcloseInfo;
                }
            }
        }

        /// <summary>
        /// The NewProjectAppFolder folder.
        /// </summary>
        [RepositoryFolder("d02feddb-2a8b-4a3a-9412-edeedfb71fa5")]
        public partial class NewProjectAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _databaseschemaanddataimportlistitemInfo;
            RepoItemInfo _folderpathtextboxInfo;
            RepoItemInfo _okbuttonInfo;
            RepoItemInfo _browsebuttonInfo;

            /// <summary>
            /// Creates a new NewProject  folder.
            /// </summary>
            public NewProjectAppFolder(RepoGenBaseFolder parentFolder) :
                    base("NewProject", "/form[@title='New Project']", parentFolder, 30000, null, true, "d02feddb-2a8b-4a3a-9412-edeedfb71fa5", "")
            {
                _databaseschemaanddataimportlistitemInfo = new RepoItemInfo(this, "DatabaseSchemaAndDataImportListItem", ".//container[@name='templatePanel']//list[@name='options']/listitem[@text~'^Database\\ Schema\\ and\\ Data\\ ']", 30000, null, "041ad1d6-2d22-4d63-b888-72ebf5369847");
                _folderpathtextboxInfo = new RepoItemInfo(this, "FolderPathTextbox", ".//container[@type='JPanel']//text[@name='projectFolderField']", 30000, null, "7f8e838a-ad7d-4ae9-860c-82a45fbfccbd");
                _okbuttonInfo = new RepoItemInfo(this, "OkButton", ".//container[@name='buttonPanel']/button[@text='Create']", 30000, null, "cd6965d6-c947-49b8-895d-7a749db3c59c");
                _browsebuttonInfo = new RepoItemInfo(this, "BrowseButton", ".//container[@type='JPanel']//button[@text='...']", 30000, null, "a4a05c49-b9c9-4245-87c3-e959eb48334d");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("d02feddb-2a8b-4a3a-9412-edeedfb71fa5")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("d02feddb-2a8b-4a3a-9412-edeedfb71fa5")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The DatabaseSchemaAndDataImportListItem item.
            /// </summary>
            [RepositoryItem("041ad1d6-2d22-4d63-b888-72ebf5369847")]
            public virtual Ranorex.ListItem DatabaseSchemaAndDataImportListItem
            {
                get
                {
                    return _databaseschemaanddataimportlistitemInfo.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The DatabaseSchemaAndDataImportListItem item info.
            /// </summary>
            [RepositoryItemInfo("041ad1d6-2d22-4d63-b888-72ebf5369847")]
            public virtual RepoItemInfo DatabaseSchemaAndDataImportListItemInfo
            {
                get
                {
                    return _databaseschemaanddataimportlistitemInfo;
                }
            }

            /// <summary>
            /// The FolderPathTextbox item.
            /// </summary>
            [RepositoryItem("7f8e838a-ad7d-4ae9-860c-82a45fbfccbd")]
            public virtual Ranorex.Text FolderPathTextbox
            {
                get
                {
                    return _folderpathtextboxInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The FolderPathTextbox item info.
            /// </summary>
            [RepositoryItemInfo("7f8e838a-ad7d-4ae9-860c-82a45fbfccbd")]
            public virtual RepoItemInfo FolderPathTextboxInfo
            {
                get
                {
                    return _folderpathtextboxInfo;
                }
            }

            /// <summary>
            /// The OkButton item.
            /// </summary>
            [RepositoryItem("cd6965d6-c947-49b8-895d-7a749db3c59c")]
            public virtual Ranorex.Button OkButton
            {
                get
                {
                    return _okbuttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The OkButton item info.
            /// </summary>
            [RepositoryItemInfo("cd6965d6-c947-49b8-895d-7a749db3c59c")]
            public virtual RepoItemInfo OkButtonInfo
            {
                get
                {
                    return _okbuttonInfo;
                }
            }

            /// <summary>
            /// The BrowseButton item.
            /// </summary>
            [RepositoryItem("a4a05c49-b9c9-4245-87c3-e959eb48334d")]
            public virtual Ranorex.Button BrowseButton
            {
                get
                {
                    return _browsebuttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The BrowseButton item info.
            /// </summary>
            [RepositoryItemInfo("a4a05c49-b9c9-4245-87c3-e959eb48334d")]
            public virtual RepoItemInfo BrowseButtonInfo
            {
                get
                {
                    return _browsebuttonInfo;
                }
            }
        }

        /// <summary>
        /// The SelectFolderAppFolder folder.
        /// </summary>
        [RepositoryFolder("2af9e6c0-4bdb-401e-888d-e47d2b34d714")]
        public partial class SelectFolderAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _folderpathtextboxInfo;
            RepoItemInfo _selectbuttonInfo;

            /// <summary>
            /// Creates a new SelectFolder  folder.
            /// </summary>
            public SelectFolderAppFolder(RepoGenBaseFolder parentFolder) :
                    base("SelectFolder", "/form[@title='Select Folder']", parentFolder, 30000, null, true, "2af9e6c0-4bdb-401e-888d-e47d2b34d714", "")
            {
                _folderpathtextboxInfo = new RepoItemInfo(this, "FolderPathTextbox", "element/container[@type='JPanel']/container[3]/container[2]/text[@accessiblename='Folder name:']", 30000, null, "6e9d1775-5487-44de-9695-e43ba63f7d0a");
                _selectbuttonInfo = new RepoItemInfo(this, "SelectButton", "element/container[@type='JPanel']/container[3]/container[3]/button[@text='Select']", 30000, null, "54eb4a75-968e-4fae-ad2c-8c8f01de794b");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("2af9e6c0-4bdb-401e-888d-e47d2b34d714")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("2af9e6c0-4bdb-401e-888d-e47d2b34d714")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The FolderPathTextbox item.
            /// </summary>
            [RepositoryItem("6e9d1775-5487-44de-9695-e43ba63f7d0a")]
            public virtual Ranorex.Text FolderPathTextbox
            {
                get
                {
                    return _folderpathtextboxInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The FolderPathTextbox item info.
            /// </summary>
            [RepositoryItemInfo("6e9d1775-5487-44de-9695-e43ba63f7d0a")]
            public virtual RepoItemInfo FolderPathTextboxInfo
            {
                get
                {
                    return _folderpathtextboxInfo;
                }
            }

            /// <summary>
            /// The SelectButton item.
            /// </summary>
            [RepositoryItem("54eb4a75-968e-4fae-ad2c-8c8f01de794b")]
            public virtual Ranorex.Button SelectButton
            {
                get
                {
                    return _selectbuttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The SelectButton item info.
            /// </summary>
            [RepositoryItemInfo("54eb4a75-968e-4fae-ad2c-8c8f01de794b")]
            public virtual RepoItemInfo SelectButtonInfo
            {
                get
                {
                    return _selectbuttonInfo;
                }
            }
        }

        /// <summary>
        /// The SunAwtWindowAppFolder folder.
        /// </summary>
        [RepositoryFolder("f97fffa4-056e-4948-845a-822db07e8f2c")]
        public partial class SunAwtWindowAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _newInfo;
            RepoItemInfo _newfolderInfo;

            /// <summary>
            /// Creates a new SunAwtWindow  folder.
            /// </summary>
            public SunAwtWindowAppFolder(RepoGenBaseFolder parentFolder) :
                    base("SunAwtWindow", "/form[@class='SunAwtWindow']", parentFolder, 30000, null, true, "f97fffa4-056e-4948-845a-822db07e8f2c", "")
            {
                _newInfo = new RepoItemInfo(this, "New", ".//menuitem[@text='New']", 30000, null, "c7b0139c-1405-4228-a3e8-5a5fb12f8ca9");
                _newfolderInfo = new RepoItemInfo(this, "NewFolder", ".//menuitem[@text='New Folder']", 30000, null, "d6223d81-3929-49b5-b470-56f0db5a5d80");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("f97fffa4-056e-4948-845a-822db07e8f2c")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("f97fffa4-056e-4948-845a-822db07e8f2c")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The New item.
            /// </summary>
            [RepositoryItem("c7b0139c-1405-4228-a3e8-5a5fb12f8ca9")]
            public virtual Ranorex.MenuItem New
            {
                get
                {
                    return _newInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The New item info.
            /// </summary>
            [RepositoryItemInfo("c7b0139c-1405-4228-a3e8-5a5fb12f8ca9")]
            public virtual RepoItemInfo NewInfo
            {
                get
                {
                    return _newInfo;
                }
            }

            /// <summary>
            /// The NewFolder item.
            /// </summary>
            [RepositoryItem("d6223d81-3929-49b5-b470-56f0db5a5d80")]
            public virtual Ranorex.MenuItem NewFolder
            {
                get
                {
                    return _newfolderInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The NewFolder item info.
            /// </summary>
            [RepositoryItemInfo("d6223d81-3929-49b5-b470-56f0db5a5d80")]
            public virtual RepoItemInfo NewFolderInfo
            {
                get
                {
                    return _newfolderInfo;
                }
            }
        }

        /// <summary>
        /// The NewFolderMenuAppFolder folder.
        /// </summary>
        [RepositoryFolder("6f1bd976-6b22-42da-af66-c0ade1fc2460")]
        public partial class NewFolderMenuAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _foldernameInfo;
            RepoItemInfo _okbuttonInfo;

            /// <summary>
            /// Creates a new NewFolderMenu  folder.
            /// </summary>
            public NewFolderMenuAppFolder(RepoGenBaseFolder parentFolder) :
                    base("NewFolderMenu", "/form[@title='New Folder']", parentFolder, 30000, null, true, "6f1bd976-6b22-42da-af66-c0ade1fc2460", "")
            {
                _foldernameInfo = new RepoItemInfo(this, "FolderName", ".//container[@name='OptionPane.realBody']/container[@name='OptionPane.body']/text[@name='OptionPane.textField']", 30000, null, "2eaecb1d-7ba3-44dd-9605-1e616d423f11");
                _okbuttonInfo = new RepoItemInfo(this, "OkButton", ".//container[@name='OptionPane.buttonArea']/button[@text='OK']", 30000, null, "065660cf-565a-4104-bfc5-b00b9ce77fbc");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("6f1bd976-6b22-42da-af66-c0ade1fc2460")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("6f1bd976-6b22-42da-af66-c0ade1fc2460")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The FolderName item.
            /// </summary>
            [RepositoryItem("2eaecb1d-7ba3-44dd-9605-1e616d423f11")]
            public virtual Ranorex.Text FolderName
            {
                get
                {
                    return _foldernameInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The FolderName item info.
            /// </summary>
            [RepositoryItemInfo("2eaecb1d-7ba3-44dd-9605-1e616d423f11")]
            public virtual RepoItemInfo FolderNameInfo
            {
                get
                {
                    return _foldernameInfo;
                }
            }

            /// <summary>
            /// The OkButton item.
            /// </summary>
            [RepositoryItem("065660cf-565a-4104-bfc5-b00b9ce77fbc")]
            public virtual Ranorex.Button OkButton
            {
                get
                {
                    return _okbuttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The OkButton item info.
            /// </summary>
            [RepositoryItemInfo("065660cf-565a-4104-bfc5-b00b9ce77fbc")]
            public virtual RepoItemInfo OkButtonInfo
            {
                get
                {
                    return _okbuttonInfo;
                }
            }
        }

        /// <summary>
        /// The SelectDirectoryAppFolder folder.
        /// </summary>
        [RepositoryFolder("95e09dfb-ca22-4e31-985c-b201f4d7c683")]
        public partial class SelectDirectoryAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _localmachinepathInfo;
            RepoItemInfo _selectbuttonInfo;
            RepoItemInfo _filepathInfo;

            /// <summary>
            /// Creates a new SelectDirectory  folder.
            /// </summary>
            public SelectDirectoryAppFolder(RepoGenBaseFolder parentFolder) :
                    base("SelectDirectory", "/form[@title='Select Directory']", parentFolder, 30000, null, true, "95e09dfb-ca22-4e31-985c-b201f4d7c683", "")
            {
                _localmachinepathInfo = new RepoItemInfo(this, "LocalMachinePath", ".//container[2]/container[1]/text[@type='JTextField']", 30000, null, "599d493e-fc3e-4288-a403-b527a219be95");
                _selectbuttonInfo = new RepoItemInfo(this, "SelectButton", ".//container[@type='ButtonPanel']/button[@name='defaultButton']", 30000, null, "3d97b912-a635-44bf-8d00-e2736a647a10");
                _filepathInfo = new RepoItemInfo(this, "FilePath", "container[2]/container[2]/?/?/container[@name='viewport']/tree[@type='BasicFileSystemTree']//treeitem[@text='C:\\DDL']", 30000, null, "72555930-b675-4a72-802d-1ad29de69121");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("95e09dfb-ca22-4e31-985c-b201f4d7c683")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("95e09dfb-ca22-4e31-985c-b201f4d7c683")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The LocalMachinePath item.
            /// </summary>
            [RepositoryItem("599d493e-fc3e-4288-a403-b527a219be95")]
            public virtual Ranorex.Text LocalMachinePath
            {
                get
                {
                    return _localmachinepathInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The LocalMachinePath item info.
            /// </summary>
            [RepositoryItemInfo("599d493e-fc3e-4288-a403-b527a219be95")]
            public virtual RepoItemInfo LocalMachinePathInfo
            {
                get
                {
                    return _localmachinepathInfo;
                }
            }

            /// <summary>
            /// The SelectButton item.
            /// </summary>
            [RepositoryItem("3d97b912-a635-44bf-8d00-e2736a647a10")]
            public virtual Ranorex.Button SelectButton
            {
                get
                {
                    return _selectbuttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The SelectButton item info.
            /// </summary>
            [RepositoryItemInfo("3d97b912-a635-44bf-8d00-e2736a647a10")]
            public virtual RepoItemInfo SelectButtonInfo
            {
                get
                {
                    return _selectbuttonInfo;
                }
            }

            /// <summary>
            /// The FilePath item.
            /// </summary>
            [RepositoryItem("72555930-b675-4a72-802d-1ad29de69121")]
            public virtual Ranorex.TreeItem FilePath
            {
                get
                {
                    return _filepathInfo.CreateAdapter<Ranorex.TreeItem>(true);
                }
            }

            /// <summary>
            /// The FilePath item info.
            /// </summary>
            [RepositoryItemInfo("72555930-b675-4a72-802d-1ad29de69121")]
            public virtual RepoItemInfo FilePathInfo
            {
                get
                {
                    return _filepathInfo;
                }
            }
        }

        /// <summary>
        /// The DatabaseAppFolder folder.
        /// </summary>
        [RepositoryFolder("af523b1f-5e4b-40cd-ba8d-eb21fab8a136")]
        public partial class DatabaseAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _localserversInfo;
            RepoItemInfo _amazonredshiftInfo;
            RepoItemInfo _openingqaInfo;
            RepoItemInfo _opentexteditorInfo;

            /// <summary>
            /// Creates a new Database  folder.
            /// </summary>
            public DatabaseAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Database", "/form[@title='Choose Server or Database']", parentFolder, 30000, null, true, "af523b1f-5e4b-40cd-ba8d-eb21fab8a136", "")
            {
                _localserversInfo = new RepoItemInfo(this, "LocalServers", ".//container[@type='JScrollPane']/container[@name='viewport']/tree[@name='dmu']/?/?/treeitem[@text='Local Database Servers']", 30000, null, "702902cb-956e-4c1d-ad9a-03a5666be411");
                _amazonredshiftInfo = new RepoItemInfo(this, "AmazonRedshift", ".//container[@type='JScrollPane']/container[@name='viewport']/tree[@name='tree']//treeitem[@text='Amazon Redshift']", 30000, null, "99810501-89cb-4755-be55-9cb6a7a75106");
                _openingqaInfo = new RepoItemInfo(this, "OpeningQA", ".//button[@name='defaultButton']", 30000, null, "540ce1c0-a3a0-4f78-8ff9-3ddecc25f04c");
                _opentexteditorInfo = new RepoItemInfo(this, "OpenTextEditor", ".//button[@text='Open in Text Editor']", 30000, null, "fb620f74-a3de-458d-8369-48736f2f0c9d");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("af523b1f-5e4b-40cd-ba8d-eb21fab8a136")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("af523b1f-5e4b-40cd-ba8d-eb21fab8a136")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The LocalServers item.
            /// </summary>
            [RepositoryItem("702902cb-956e-4c1d-ad9a-03a5666be411")]
            public virtual Ranorex.TreeItem LocalServers
            {
                get
                {
                    return _localserversInfo.CreateAdapter<Ranorex.TreeItem>(true);
                }
            }

            /// <summary>
            /// The LocalServers item info.
            /// </summary>
            [RepositoryItemInfo("702902cb-956e-4c1d-ad9a-03a5666be411")]
            public virtual RepoItemInfo LocalServersInfo
            {
                get
                {
                    return _localserversInfo;
                }
            }

            /// <summary>
            /// The AmazonRedshift item.
            /// </summary>
            [RepositoryItem("99810501-89cb-4755-be55-9cb6a7a75106")]
            public virtual Ranorex.TreeItem AmazonRedshift
            {
                get
                {
                    return _amazonredshiftInfo.CreateAdapter<Ranorex.TreeItem>(true);
                }
            }

            /// <summary>
            /// The AmazonRedshift item info.
            /// </summary>
            [RepositoryItemInfo("99810501-89cb-4755-be55-9cb6a7a75106")]
            public virtual RepoItemInfo AmazonRedshiftInfo
            {
                get
                {
                    return _amazonredshiftInfo;
                }
            }

            /// <summary>
            /// The OpeningQA item.
            /// </summary>
            [RepositoryItem("540ce1c0-a3a0-4f78-8ff9-3ddecc25f04c")]
            public virtual Ranorex.Button OpeningQA
            {
                get
                {
                    return _openingqaInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The OpeningQA item info.
            /// </summary>
            [RepositoryItemInfo("540ce1c0-a3a0-4f78-8ff9-3ddecc25f04c")]
            public virtual RepoItemInfo OpeningQAInfo
            {
                get
                {
                    return _openingqaInfo;
                }
            }

            /// <summary>
            /// The OpenTextEditor item.
            /// </summary>
            [RepositoryItem("fb620f74-a3de-458d-8369-48736f2f0c9d")]
            public virtual Ranorex.Button OpenTextEditor
            {
                get
                {
                    return _opentexteditorInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The OpenTextEditor item info.
            /// </summary>
            [RepositoryItemInfo("fb620f74-a3de-458d-8369-48736f2f0c9d")]
            public virtual RepoItemInfo OpenTextEditorInfo
            {
                get
                {
                    return _opentexteditorInfo;
                }
            }
        }

        /// <summary>
        /// The UnmountWindowAppFolder folder.
        /// </summary>
        [RepositoryFolder("6832c317-8695-44d6-92f6-1a1539f35bea")]
        public partial class UnmountWindowAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _yesbuttonInfo;

            /// <summary>
            /// Creates a new UnmountWindow  folder.
            /// </summary>
            public UnmountWindowAppFolder(RepoGenBaseFolder parentFolder) :
                    base("UnmountWindow", "/form[@title='Unmount']", parentFolder, 30000, null, true, "6832c317-8695-44d6-92f6-1a1539f35bea", "")
            {
                _yesbuttonInfo = new RepoItemInfo(this, "YesButton", ".//container[@name='OptionPane.buttonArea']/button[@text='Yes']", 30000, null, "2078072e-05ce-440e-bb0b-669f7fe24dd7");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("6832c317-8695-44d6-92f6-1a1539f35bea")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("6832c317-8695-44d6-92f6-1a1539f35bea")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The YesButton item.
            /// </summary>
            [RepositoryItem("2078072e-05ce-440e-bb0b-669f7fe24dd7")]
            public virtual Ranorex.Button YesButton
            {
                get
                {
                    return _yesbuttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The YesButton item info.
            /// </summary>
            [RepositoryItemInfo("2078072e-05ce-440e-bb0b-669f7fe24dd7")]
            public virtual RepoItemInfo YesButtonInfo
            {
                get
                {
                    return _yesbuttonInfo;
                }
            }
        }

        /// <summary>
        /// The DeleteConfirmAppFolder folder.
        /// </summary>
        [RepositoryFolder("73f582aa-fbfe-4e2c-8d61-6c3b8371b3ff")]
        public partial class DeleteConfirmAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _yesbuttonInfo;

            /// <summary>
            /// Creates a new DeleteConfirm  folder.
            /// </summary>
            public DeleteConfirmAppFolder(RepoGenBaseFolder parentFolder) :
                    base("DeleteConfirm", "/form[@title='Delete']", parentFolder, 30000, null, true, "73f582aa-fbfe-4e2c-8d61-6c3b8371b3ff", "")
            {
                _yesbuttonInfo = new RepoItemInfo(this, "YesButton", ".//container[@name='OptionPane.buttonArea']/button[@text='Yes']", 30000, null, "19d8a30f-5e8a-4903-a180-dee2bac38d6d");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("73f582aa-fbfe-4e2c-8d61-6c3b8371b3ff")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("73f582aa-fbfe-4e2c-8d61-6c3b8371b3ff")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The YesButton item.
            /// </summary>
            [RepositoryItem("19d8a30f-5e8a-4903-a180-dee2bac38d6d")]
            public virtual Ranorex.Button YesButton
            {
                get
                {
                    return _yesbuttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The YesButton item info.
            /// </summary>
            [RepositoryItemInfo("19d8a30f-5e8a-4903-a180-dee2bac38d6d")]
            public virtual RepoItemInfo YesButtonInfo
            {
                get
                {
                    return _yesbuttonInfo;
                }
            }
        }

        /// <summary>
        /// The RemoveWindowAppFolder folder.
        /// </summary>
        [RepositoryFolder("b431ad76-6e70-4944-a77f-5314099520fe")]
        public partial class RemoveWindowAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _yesbuttonInfo;

            /// <summary>
            /// Creates a new RemoveWindow  folder.
            /// </summary>
            public RemoveWindowAppFolder(RepoGenBaseFolder parentFolder) :
                    base("RemoveWindow", "/form[@title='Remove']", parentFolder, 30000, null, true, "b431ad76-6e70-4944-a77f-5314099520fe", "")
            {
                _yesbuttonInfo = new RepoItemInfo(this, "YesButton", ".//container[@name='OptionPane.buttonArea']/button[@text='Yes']", 30000, null, "3eb912ca-d622-4648-a206-404b7bd174fe");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("b431ad76-6e70-4944-a77f-5314099520fe")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("b431ad76-6e70-4944-a77f-5314099520fe")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The YesButton item.
            /// </summary>
            [RepositoryItem("3eb912ca-d622-4648-a206-404b7bd174fe")]
            public virtual Ranorex.Button YesButton
            {
                get
                {
                    return _yesbuttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The YesButton item info.
            /// </summary>
            [RepositoryItemInfo("3eb912ca-d622-4648-a206-404b7bd174fe")]
            public virtual RepoItemInfo YesButtonInfo
            {
                get
                {
                    return _yesbuttonInfo;
                }
            }
        }

        /// <summary>
        /// The DataTreeAppFolder folder.
        /// </summary>
        [RepositoryFolder("457b1bc5-42ac-4276-a434-1b44c66a2912")]
        public partial class DataTreeAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _aquascriptsInfo;
            RepoItemInfo _serversInfo;
            RepoItemInfo _userfilesInfo;
            RepoItemInfo _templatetreeInfo;
            RepoItemInfo _tabInfo;
            RepoItemInfo _newprojectfileInfo;

            /// <summary>
            /// Creates a new DataTree  folder.
            /// </summary>
            public DataTreeAppFolder(RepoGenBaseFolder parentFolder) :
                    base("DataTree", "/form[@title~'^Aqua\\ Data\\ Studio\\ \\[Databas']", parentFolder, 30000, null, true, "457b1bc5-42ac-4276-a434-1b44c66a2912", "")
            {
                _aquascriptsInfo = new RepoItemInfo(this, "AquaScripts", ".//container[@type='ToolWindowsPane']/container[@name='myLayeredPane']/container[@name='myVerticalSplitter']/container[@name='myInnerComponent']/container[@name='myFirstComponent']/?/?/container[@type='NonOpaquePanel']//container[@name='viewport']/tree[@name='projectTree']//treeitem[@text='AquaScripts']", 30000, null, "eab692b4-ea28-4944-bdd9-97fd6ec47bde");
                _serversInfo = new RepoItemInfo(this, "Servers", ".//container[@type='ToolWindowsPane']/container[@name='myLayeredPane']/container[@name='myVerticalSplitter']/container[@name='myInnerComponent']/container[@name='myFirstComponent']/?/?/container[@type='NonOpaquePanel']//container[@name='viewport']/tree[@name='projectTree']//treeitem[@text='Servers']", 30000, null, "33a20079-26e5-4991-865e-a09c4f2914d5");
                _userfilesInfo = new RepoItemInfo(this, "UserFiles", ".//container[@type='ToolWindowsPane']/container[@name='myLayeredPane']/container[@name='myVerticalSplitter']/container[@name='myInnerComponent']/container[@name='myFirstComponent']/?/?/container[@type='NonOpaquePanel']//container[@name='viewport']/tree[@name='projectTree']//treeitem[@text='User Files']", 30000, null, "af751947-2c46-4938-90d0-d9e0c4b321e1");
                _templatetreeInfo = new RepoItemInfo(this, "TemplateTree", ".//container[@type='ToolWindowsPane']/container[@name='myLayeredPane']/container[@name='myVerticalSplitter']/container[@name='myInnerComponent']/container[@name='myFirstComponent']//container[@name='viewport']/tree[@name='projectTree']/?/?/treeitem[@text~'^Database\\ Schema\\ and\\ Data\\ ']", 30000, null, "ba579be9-bf8b-4384-a1e1-ddd9974846db");
                _tabInfo = new RepoItemInfo(this, "Tab", ".//container[@type='ToolWindowsPane']/container[@name='myLayeredPane']//container[@type='PlatDockingContentPanel']//tabpage[@title~'^Database\\ Schema\\ and\\ Data\\ ']", 30000, null, "c80fabc3-032d-4c14-9baf-fd1ec417da05");
                _newprojectfileInfo = new RepoItemInfo(this, "NewProjectfile", ".//container[@type='ToolWindowsPane']/container[@name='myLayeredPane']/container[@name='myVerticalSplitter']/container[@name='myInnerComponent']/container[@name='myFirstComponent']//container[@name='viewport']/tree[@name='projectTree']/?/?/treeitem[@text~'^Database\\ Schema\\ and\\ Data\\ ']", 30000, null, "522fa866-a439-4787-bd9b-c036dd3c7341");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("457b1bc5-42ac-4276-a434-1b44c66a2912")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("457b1bc5-42ac-4276-a434-1b44c66a2912")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The AquaScripts item.
            /// </summary>
            [RepositoryItem("eab692b4-ea28-4944-bdd9-97fd6ec47bde")]
            public virtual Ranorex.TreeItem AquaScripts
            {
                get
                {
                    return _aquascriptsInfo.CreateAdapter<Ranorex.TreeItem>(true);
                }
            }

            /// <summary>
            /// The AquaScripts item info.
            /// </summary>
            [RepositoryItemInfo("eab692b4-ea28-4944-bdd9-97fd6ec47bde")]
            public virtual RepoItemInfo AquaScriptsInfo
            {
                get
                {
                    return _aquascriptsInfo;
                }
            }

            /// <summary>
            /// The Servers item.
            /// </summary>
            [RepositoryItem("33a20079-26e5-4991-865e-a09c4f2914d5")]
            public virtual Ranorex.TreeItem Servers
            {
                get
                {
                    return _serversInfo.CreateAdapter<Ranorex.TreeItem>(true);
                }
            }

            /// <summary>
            /// The Servers item info.
            /// </summary>
            [RepositoryItemInfo("33a20079-26e5-4991-865e-a09c4f2914d5")]
            public virtual RepoItemInfo ServersInfo
            {
                get
                {
                    return _serversInfo;
                }
            }

            /// <summary>
            /// The UserFiles item.
            /// </summary>
            [RepositoryItem("af751947-2c46-4938-90d0-d9e0c4b321e1")]
            public virtual Ranorex.TreeItem UserFiles
            {
                get
                {
                    return _userfilesInfo.CreateAdapter<Ranorex.TreeItem>(true);
                }
            }

            /// <summary>
            /// The UserFiles item info.
            /// </summary>
            [RepositoryItemInfo("af751947-2c46-4938-90d0-d9e0c4b321e1")]
            public virtual RepoItemInfo UserFilesInfo
            {
                get
                {
                    return _userfilesInfo;
                }
            }

            /// <summary>
            /// The TemplateTree item.
            /// </summary>
            [RepositoryItem("ba579be9-bf8b-4384-a1e1-ddd9974846db")]
            public virtual Ranorex.TreeItem TemplateTree
            {
                get
                {
                    return _templatetreeInfo.CreateAdapter<Ranorex.TreeItem>(true);
                }
            }

            /// <summary>
            /// The TemplateTree item info.
            /// </summary>
            [RepositoryItemInfo("ba579be9-bf8b-4384-a1e1-ddd9974846db")]
            public virtual RepoItemInfo TemplateTreeInfo
            {
                get
                {
                    return _templatetreeInfo;
                }
            }

            /// <summary>
            /// The Tab item.
            /// </summary>
            [RepositoryItem("c80fabc3-032d-4c14-9baf-fd1ec417da05")]
            public virtual Ranorex.TabPage Tab
            {
                get
                {
                    return _tabInfo.CreateAdapter<Ranorex.TabPage>(true);
                }
            }

            /// <summary>
            /// The Tab item info.
            /// </summary>
            [RepositoryItemInfo("c80fabc3-032d-4c14-9baf-fd1ec417da05")]
            public virtual RepoItemInfo TabInfo
            {
                get
                {
                    return _tabInfo;
                }
            }

            /// <summary>
            /// The NewProjectfile item.
            /// </summary>
            [RepositoryItem("522fa866-a439-4787-bd9b-c036dd3c7341")]
            public virtual Ranorex.TreeItem NewProjectfile
            {
                get
                {
                    return _newprojectfileInfo.CreateAdapter<Ranorex.TreeItem>(true);
                }
            }

            /// <summary>
            /// The NewProjectfile item info.
            /// </summary>
            [RepositoryItemInfo("522fa866-a439-4787-bd9b-c036dd3c7341")]
            public virtual RepoItemInfo NewProjectfileInfo
            {
                get
                {
                    return _newprojectfileInfo;
                }
            }
        }

        /// <summary>
        /// The DB2WindowsAppFolder folder.
        /// </summary>
        [RepositoryFolder("ffab8a1f-e8e3-4af5-9ee3-8ff3682d839d")]
        public partial class DB2WindowsAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _windowstabsInfo;

            /// <summary>
            /// Creates a new DB2Windows  folder.
            /// </summary>
            public DB2WindowsAppFolder(RepoGenBaseFolder parentFolder) :
                    base("DB2Windows", "/form[@title~'^Aqua\\ Data\\ Studio\\ \\[DB2LUW\\.']", parentFolder, 30000, null, true, "ffab8a1f-e8e3-4af5-9ee3-8ff3682d839d", "")
            {
                _windowstabsInfo = new RepoItemInfo(this, "WindowsTabs", ".//container[@type='ToolWindowsPane']/container[@name='myLayeredPane']//container[@type='PlatDockingContentPanel']//tabpage[@title~'^root@Amazon\\ Redshift\\ \\[DB2']", 30000, null, "6911395a-d7b0-494a-9d1e-cbc9db9b4b68");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("ffab8a1f-e8e3-4af5-9ee3-8ff3682d839d")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("ffab8a1f-e8e3-4af5-9ee3-8ff3682d839d")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The WindowsTabs item.
            /// </summary>
            [RepositoryItem("6911395a-d7b0-494a-9d1e-cbc9db9b4b68")]
            public virtual Ranorex.TabPage WindowsTabs
            {
                get
                {
                    return _windowstabsInfo.CreateAdapter<Ranorex.TabPage>(true);
                }
            }

            /// <summary>
            /// The WindowsTabs item info.
            /// </summary>
            [RepositoryItemInfo("6911395a-d7b0-494a-9d1e-cbc9db9b4b68")]
            public virtual RepoItemInfo WindowsTabsInfo
            {
                get
                {
                    return _windowstabsInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}